CALL SYSCS_UTIL.SYSCS_SET_RUNTIMESTATISTICS(1);
CALL SYSCS_UTIL.SYSCS_SET_STATISTICS_TIMING(1);

SELECT 
	    "IDENTITY".*, 
	    MEMBER_EVENT.* 
	  FROM 
	    "IDENTITY", 
	    MEMBER_EVENT 
	  WHERE 
	    "IDENTITY".IDENTITY_SID = MEMBER_EVENT.MEMBER_EVENT_LOCATION_SID AND 
	    ( MEMBER_EVENT.EVENT_TYPE_SID = 31 OR
	        MEMBER_EVENT.EVENT_TYPE_SID = 33 ) AND 
	    MEMBER_EVENT.MEMBER_SID = 5561 
	  ORDER BY 
	    MEMBER_EVENT.MEMBER_EVENT_DATE DESC;
			    
VALUES SYSCS_UTIL.SYSCS_GET_RUNTIMESTATISTICS();

CALL SYSCS_UTIL.SYSCS_SET_RUNTIMESTATISTICS(0);
CALL SYSCS_UTIL.SYSCS_SET_STATISTICS_TIMING(0);

-- -----------------------------------------------------------------------------
SELECT
	   "IDENTITY".*, 
	   MEMBER.*, 
	   SUBSCRIPTION.* 
	 FROM 
	   "IDENTITY", 
	   MEMBER, 
	   SUBSCRIPTION 
	 WHERE 
	   SUBSCRIPTION.SUBSCRIPTION_USERNAME = 'echarles' AND 
	   SUBSCRIPTION.DRIVER_SID = 100 AND 
	   SUBSCRIPTION.MEMBER_SID = MEMBER.MEMBER_SID AND 
	   "IDENTITY".IDENTITY_SID = MEMBER.IDENTITY_LOCATION_SID AND 
	   MEMBER.COMMUNITY_SID = 100;

-- -----------------------------------------------------------------------------
			SELECT 
 			  "IDENTITY".*, 
 			  SUBSCRIPTION.*, 
			  MEMBER.* 
			 FROM 
 			  "IDENTITY", 
			  SUBSCRIPTION, 
			  MEMBER 
			 WHERE 
			  UPPER(SUBSCRIPTION.SUBSCRIPTION_USERNAME) = UPPER('echarles') AND 
			  SUBSCRIPTION.DRIVER_SID = 100 AND 
			  SUBSCRIPTION.MEMBER_SID = MEMBER.MEMBER_SID AND 
			  "IDENTITY".IDENTITY_SID = MEMBER.IDENTITY_SID AND 
			  MEMBER.COMMUNITY_SID = 100;

-- -----------------------------------------------------------------------------
