DELETE FROM SCHEDULE_INFO ;
DELETE FROM SCHEDULE ;
DELETE FROM JOB;
DELETE FROM ITEM_BUNDLE_I18N ;
DELETE FROM ITEM_BUNDLE_ASS ;
DELETE FROM ITEM_BUNDLE ;
DELETE FROM ITEM_I18N ;
DELETE FROM ITEM ;
