#!/bin/bash

# Licensed to the AOS Community (AOS) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The AOS licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

aos-jdk-8

cd /c/spark.git
rm spark-assembly_*-dist.tgz

make-distribution.sh --hadoop 2.4.0 --tgz --with-yarn --with-hive --name 2.4.0

rm -fr $SPARK_HOME
mkdir $SPARK_HOME

# hacky...
cp spark-*-bin-*.tgz /opt
cd /opt
tar xvfz spark-*-bin-*.tgz

cd $SPARK_HOME/sbin

