#!/bin/bash

# Licensed to the AOS Community (AOS) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The AOS licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

source datalayer-console-colors

echo -e "---------------------------------------"
echo -e " ____      _       _                   "
echo -e "|    \ ___| |_ ___| |___ _ _ ___ ___   "
echo -e "|  |  | .'|  _| .'| | .'| | | -_|  _|  "
echo -e "|____/|__,|_| |__,|_|__,|_  |___|_|    "
echo -e "                        |___|          "
echo -e " "$COLOR_OK"#"$COLOR_ERR"data"$COLOR_WARN"layer"$COLOR_NO
echo -e "---------------------------------------"
echo
