#!/bin/bash

# Licensed to the AOS Community (AOS) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The AOS licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

#protoc-2.5.0
source aos-jdk-7

cd /c/hadoop.git
mvn clean
mvn install -Pdist -Dtar -DskipTests
rm -fr $HADOOP_HOME
cp hadoop-dist/target/hadoop-*-SNAPSHOT.tar.gz /opt
cd /opt
tar xvfz hadoop-*-SNAPSHOT.tar.gz
rm hadoop-*-SNAPSHOT.tar.gz

cd $HADOOP_HOME/bin

cp $DATALAYER_SRC_HOME/hadoop/common/src/main/resources/io/aos/hadoop/h3/distributed/* $HADOOP_HOME/etc/hadoop
#cp $DATALAYER_SRC_HOME/hadoop/common/src/main/resources/io/aos/hadoop/h3/local/* $HADOOP_HOME/etc/hadoop
#cp $DATALAYER_SRC_HOME/hadoop/common/src/main/resources/io/aos/hadoop/h2/distributed/* $HADOOP_HOME/etc/hadoop
#cp $DATALAYER_SRC_HOME/hadoop/common/src/main/resources/io/aos/hadoop/h2/local/* $HADOOP_HOME/etc/hadoop

