#!/bin/bash

# Licensed to the AOS Community (AOS) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The AOS licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

#protoc-2.5.0
source aos-jdk-6

cd /c/hbase.git

mvn clean
mvn clean install assembly:single -DskipTests
#mvn clean -Dhadoop.profile=3.0
#mvn clean install assembly:single -DskipTests -Dhadoop.profile=3.0

rm -fr $HBASE_HOME
cp hbase-assembly/target/hbase-*-SNAPSHOT-bin.tar.gz /opt
cd /opt
tar xvfz hbase-*-SNAPSHOT-bin.tar.gz
rm hbase-*-SNAPSHOT-bin.tar.gz

cd $HBASE_HOME/bin
cp $DATALAYER_SRC_HOME/hbase/common/src/main/resources/io/aos/hbase/distributed/hbase-site.xml $HBASE_HOME/conf
sed -e 's@# export JAVA_HOME=/usr/java/jdk1.6.0/@export JAVA_HOME=/opt/jdk1.7.0@' $HBASE_HOME/conf/hbase-env.sh > $HBASE_HOME/conf/hbase-env.sh-updated
mv $HBASE_HOME/conf/hbase-env.sh-updated $HBASE_HOME/conf/hbase-env.sh

