#!/bin/bash

# Licensed to the AOS Community (AOS) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The AOS licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

datalayer-echo-header

read -p "Are you sure you want to remove all Hadoop persisted files, they will be lost forever!!! (y/N)?" -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]
then

    echo 'Removing Hadoop (and HBase) files...'
    rm -fr /var/data/hadoop-3.0.0-*
    
    echo
    echo All persisted files are removed.

    echo
        
    echo Formatting Hadoop...
    echo
    
    hadoop namenode -format AosHadoopCluster
    
    echo
    echo Hadoop is now reseted and formatted.

fi

echo

datalayer-echo-footer
