#!/bin/bash

# Licensed to the AOS Community (AOS) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The AOS licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

###############################################################################
#
# [0m  reset; clears all colors and styles (to white on black)
# [1m  bold on
# [3m  italics on
# [4m  underline on
# [7m  inverse on; reverses foreground & background colors
# [9m  strikethrough on
# [22m bold off
# [23m italics off
# [24m # [27m inverse off
# [29m strikethrough off
# [30m set foreground color to black
# [31m set foreground color to red
# [32m set foreground color to green
# [33m set foreground color to yellow
# [34m set foreground color to blue
# [35m set foreground color to magenta (purple)
# [36m set foreground color to cyan
# [37m set foreground color to white
# [39m set foreground color to default (white)
# [40m set background color to black
# [41m set background color to red
# [42m set background color to green
# [43m set background color to yellow
# [44m set background color to blue
# [45m set background color to magenta (purple)
# [46m set background color to cyan
# [47m set background color to white
# [49m set background color to default (black)
#
###############################################################################

export COLOR_NO='\x1b[0m'
export COLOR_OK='\x1b[32m'
export COLOR_ERR='\x1b[31m'
export COLOR_WARN='\x1b[33m'

export MESSAGE_OK=$COLOR_OK'[OK]'$COLOR_NO
export MESSAGE_ERR=$COLOR_ERR'[ERROR]'$COLOR_NO
export MESSAGE_WARN=$COLOR_WARN'[WARN]'$COLOR_NO
