#!/bin/bash

# Licensed to the AOS Community (AOS) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The AOS licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo  ____________________________________________________________________________
echo "                                                                            "
echo "                                                                            "
echo "  _  _      __  __                      _                                   "
echo " | || | __ |  \/  |___   ___  ___ ___  | |_  ___                            "
echo " | || | __ | |\/| / _  \/   |/ _ / _  \| |_ / -_) ~ Innovative eSolutions ~ "
echo " \___ /    |_|  |_\__,_|__|_|\   \__,_|\___|\___| v. 1.0.2                  "
echo "                             _/  /                                          "
echo "                            |___/                                           "
echo "                                                                            "
echo " .: AOS Database Server Init :.                                                  "
echo "____________________________________________________________________________"
echo ...
echo Initializing AOS DB Server...
echo ...
# $Date: 2006/06/28 20:04:13 $

rm -fr DB-AOS; cp -r ini/DB-AOS .; sh datalayer-database-server-launcher
