SELECT ACCESS_CONTROL.*, ACCESS_CONTROL_TYPE.*, 
		ACTION.NAME actionName, ACTION.LABEL_KEY actionLabelKey, ACTION.SID actionSid  
		FROM ACCESS_CONTROL, ACCESS_CONTROL_TYPE, ACTION WHERE 
		ACCESS_CONTROL.IB_SID = 79
		AND ACCESS_CONTROL.ACL_TYPE_SID = ACCESS_CONTROL_TYPE.ACL_TYPE_SID
		AND ACCESS_CONTROL.ACTION_SID = ACTION.SID ;