SELECT *  FROM ITEM_BUNDLE ;


SELECT * FROM ITEM ,ITEM_I18N
WHERE ITEM.ITEM_TYPE_SID = 10
AND  ITEM.SID 
	IN (SELECT ITEM_BUNDLE_ASS.ITEM_SID FROM ITEM_BUNDLE_ASS  
		WHERE ITEM_BUNDLE_SID =1) 
		
AND ITEM_I18N.ITEM_SID = ITEM.SID ; 		
