SELECT EVENT.SID, EVENT.EVENT_DATE, EVENT_TYPE.NAME, EVENT.ITEM_DIFFUSED_SID, COMPANY.FIRSTNAME, COMPANY.NAME, EVENT.MESSAGE
	FROM EVENT, EVENT_TYPE, MEMBER, COMPANY, ITEM_DIFFUSED
		WHERE ITEM_BUNDLE_SID IN (SELECT SID FROM ITEM_BUNDLE WHERE NAME LIKE '%ecards.isabel.be%')
			AND EVENT.EVENT_TYPE_ID = EVENT_TYPE.ID
				AND EVENT.ITEM_DIFFUSED_SID = ITEM_DIFFUSED.SID
--					AND MEMBER.MEMBER_ID = ITEM_DIFFUSED.SENDER_ID
					AND MEMBER.MEMBER_ID = ITEM_DIFFUSED.RECEIVER_ID
						AND MEMBER.COMPANY_ID = COMPANY.COMPANY_ID
							AND EVENT_TYPE.NAME = 'ITEM_DIFFUSED_ACK'
