SELECT COUNT(*) FROM EVENT 
	WHERE EVENT_TYPE_ID = 1 
		AND YEAR(EVENT_DATE)= 2005 
		AND DAY(EVENT_DATE)= 19 
		AND MONTH(EVENT_DATE)=12;

SELECT COUNT(*) AS COUNT_ITEM_CREATED FROM EVENT 
	WHERE EVENT_TYPE_ID = 1 
		AND YEAR(EVENT_DATE)= 2005 
		AND DAY(EVENT_DATE)= 19 
		AND MONTH(EVENT_DATE)=12;
