SELECT * FROM ITEM_BUNDLE ;
	
SELECT ITEM_BUNDLE.*, 
			  ITEM_BUNDLE_TYPE.NAME   itemBundleTypeName, 
			  ITEM_BUNDLE_TYPE.DESCRIPTION itemBundleTypeDescription, 
			  ITEM_BUNDLE_I18N.LANGUAGE_SID itemBundleI18NLanguageSid,
			  ITEM_BUNDLE_I18N.KEYWORDS itemBundleI18NKeywords,
			  ITEM_BUNDLE_I18N.MESSAGE itemBundleI18NMessage,
			  ITEM_BUNDLE_I18N.TITLE itemBundleI18NTitle,
			  SKIN.NAME itemBundleSkinName ,
			  ITEM_BUNDLE_TYPE.NAME itemBundleTypeName,
			  ITEM_BUNDLE_TYPE.DESCRIPTION itemBundleTypeDescription
			  FROM ITEM_BUNDLE ,ITEM_BUNDLE_TYPE,SKIN ,ITEM_BUNDLE_I18N
			  WHERE MEMBER_ID =1 
			  AND   ITEM_BUNDLE_TYPE.SID = 1
			  AND ITEM_BUNDLE_I18N.ITEM_BUNDLE_SID = ITEM_BUNDLE.SID
			  AND ITEM_BUNDLE.SKIN_SID =  SKIN.SID
			  ORDER BY ITEM_BUNDLE.NAME ;	

SELECT ITEM_BUNDLE.*, 
			  ITEM_BUNDLE_TYPE.NAME   itemBundleTypeName, 
			  ITEM_BUNDLE_TYPE.DESCRIPTION itemBundleTypeDescription, 
			  ITEM_BUNDLE_I18N.LANGUAGE_SID itemBundleI18NLanguageSid,
			  ITEM_BUNDLE_I18N.KEYWORDS itemBundleI18NKeywords,
			  ITEM_BUNDLE_I18N.MESSAGE itemBundleI18NMessage,
			  ITEM_BUNDLE_I18N.TITLE itemBundleI18NTitle,
			  SKIN.NAME itemBundleSkinName, 
			  ITEM_BUNDLE_TYPE.NAME itemBundleTypeName,
			  ITEM_BUNDLE_TYPE.DESCRIPTION itemBundleTypeDescriptiON 
			  FROM ITEM_BUNDLE ,ITEM_BUNDLE_TYPE,ITEM_BUNDLE_I18N,SKIN WHERE MEMBER_ID =1 AND 
			  ITEM_BUNDLE.ITEM_BUNDLE_TY_SID = ITEM_BUNDLE_TYPE.SID  
			  AND ITEM_BUNDLE.SKIN_SID = SKIN.SID 
			  AND ITEM_BUNDLE_I18N.ITEM_BUNDLE_SID = ITEM_BUNDLE.SID
			  ORDER BY ITEM_BUNDLE.NAME ;	

			  
SELECT ITEM_BUNDLE.*, 
			  ITEM_BUNDLE_TYPE.NAME   itemBundleTypeName, 
			  ITEM_BUNDLE_TYPE.DESCRIPTION itemBundleTypeDescription, 
			  ITEM_BUNDLE_I18N.LANGUAGE_SID itemBundleI18NLanguageSid,
			  ITEM_BUNDLE_I18N.KEYWORDS itemBundleI18NKeywords,
			  ITEM_BUNDLE_I18N.MESSAGE itemBundleI18NMessage,
			  ITEM_BUNDLE_I18N.TITLE itemBundleI18NTitle,
			  SKIN.NAME itemBundleSkinName 
			  FROM ITEM_BUNDLE ,ITEM_BUNDLE_TYPE,ITEM_BUNDLE_I18N,SKIN 
			  WHERE ITEM_BUNDLE.SID = 10
			  AND ITEM_BUNDLE_I18N.ITEM_BUNDLE_SID = ITEM_BUNDLE.SID
			  AND ITEM_BUNDLE_I18N.LANGUAGE_SID = 34;
		
SELECT * FROM ITEM_BUNDLE WHERE  ITEM_BUNDLE.SERVER_NAME='www.agence-equerre.be' AND 
 ITEM_BUNDLE.ITEM_BUNDLE_TY_SID=1	;	
 
 SELECT ITEM_BUNDLE.*, 
			  ITEM_BUNDLE_TYPE.NAME   itemBundleTypeName, 
			  ITEM_BUNDLE_TYPE.DESCRIPTION itemBundleTypeDescription, 
			  ITEM_BUNDLE_I18N.LANGUAGE_SID itemBundleI18NLanguageSid,
			  ITEM_BUNDLE_I18N.KEYWORDS itemBundleI18NKeywords,
			  ITEM_BUNDLE_I18N.MESSAGE itemBundleI18NMessage,
			  ITEM_BUNDLE_I18N.TITLE itemBundleI18NTitle,
			  SKIN.NAME itemBundleSkinName 
			  FROM ITEM_BUNDLE ,ITEM_BUNDLE_TYPE,ITEM_BUNDLE_I18N,SKIN 
			  WHERE ITEM_BUNDLE_I18N.ITEM_BUNDLE_SID = ITEM_BUNDLE.SID
			  AND ITEM_BUNDLE.SKIN_SID = SKIN.SID 
			  AND ITEM_BUNDLE.ITEM_BUNDLE_TY_SID = ITEM_BUNDLE_TYPE.SID
			  AND ITEM_BUNDLE.SID = 28
			  AND ITEM_BUNDLE_I18N.LANGUAGE_SID =34 ;
			  
SELECT ITEM_BUNDLE.*,  ITEM_BUNDLE_TYPE.NAME itemBundleTypeName, ITEM_BUNDLE_TYPE.DESCRIPTION itemBundleTypeDescription, ITEM_BUNDLE_I18N.LANGUAGE_SID itemBundleLanguageSid,			  ITEM_BUNDLE_I18N.KEYWORDS itemBundleKeywords, ITEM_BUNDLE_I18N.MESSAGE itemBundleMessage,			  ITEM_BUNDLE_I18N.TITLE itemBundleTitle,			  LANGUAGE.NAME  itemBundleLanguageName 			  FROM ITEM_BUNDLE ,ITEM_BUNDLE_TYPE,ITEM_BUNDLE_I18N,SKIN,LANGUAGE 			  WHERE MEMBER_ID =1 			  AND   ITEM_BUNDLE_TYPE.SID = 1			  AND   ITEM_BUNDLE.ITEM_BUNDLE_TY_SID = ITEM_BUNDLE_TYPE.SID 			  AND   ITEM_BUNDLE.SKIN_SID = SKIN.SID 			  AND   ITEM_BUNDLE_I18N.ITEM_BUNDLE_SID = ITEM_BUNDLE.SID			  AND   ITEM_BUNDLE_I18N.LANGUAGE_SID = LANGUAGE.SID			  ORDER BY ITEM_BUNDLE.NAME ;
