SELECT PROJECT_ID FROM PROJECT ;

SELECT * FROM PROJECT WHERE PROJECT_ID = 50030;

SELECT * FROM PROJECT_INFO WHERE PROJECT_ID_INFO = 50030;

SELECT * FROM PROJECT,PROJECT_INFO 
	WHERE PROJECT_ID IN 
		(SELECT PROJECT_ID_MBR_ASS FROM PROJECT_MEMBER_ASS WHERE MEMBER_ID = 1 )
			AND PROJECT_ID_INFO IN (SELECT PROJECT_ID FROM PROJECT) 
			AND  PROJECT_ID_INFO=PROJECT_ID  
			ORDER BY NAME ASC;
