SELECT SCHEDULE.*, SCHEDULE_INFO.* 
		FROM SCHEDULE,SCHEDULE_INFO 
			WHERE SCHEDULE_INFO.INFO_PARENT_SID  
				IN (SELECT SCHEDULE_SID FROM SCHEDULE) 
						AND MEMBER_ID = 2611
						AND DATE(SCHEDULE.START_DATE)  BETWEEN '2006-08-30' AND '2006-09-30'
						AND SCHEDULE_INFO.INFO_PARENT_SID = SCHEDULE.SCHEDULE_SID  ORDER BY START_DATE	 ;
