SELECT COUNT(*) AS ALL_EVENT FROM EVENT ;
SELECT COUNT(*) AS ITEM_SENDED FROM EVENT  WHERE EVENT_TYPE_ID = 9 ;
SELECT COUNT(*) AS ITEM_CONSULTED FROM EVENT WHERE EVENT_TYPE_ID = 13 ;
SELECT COUNT(*) AS ITEM_OPENED FROM EVENT WHERE EVENT_TYPE_ID = 14 ;
