SELECT EVENT.SID,EVENT.EVENT_TYPE_ID, ITEM_DIFFUSED.TOKEN ,ITEM_DIFFUSED.DIFFUSED_TYPE_SID,
		ITEM_DIFFUSED.SENDER_ID, ITEM_DIFFUSED.RECEIVER_ID , 
		DIFFUSION.ID ,EVENT.EVENT_DATE, 
		DIFFUSION.NAME FROM  EVENT,ITEM_DIFFUSED,DIFFUSION 
			WHERE EVENT.DIFFUSION_ID= 1
				AND EVENT.ITEM_DIFFUSED_SID = ITEM_DIFFUSED.SID
				AND DIFFUSION.ID=EVENT.DIFFUSION_ID 
				ORDER BY EVENT.EVENT_DATE;
