SELECT * FROM JOB_HISTORY_INFO WHERE JOB_HISTORY_ID = 24600 
			AND COMMENT NOT LIKE '' 
			AND COMMENT NOT LIKE '%Old Task%' 
			AND COMMENT NOT LIKE '%timer%';

SELECT * FROM PROJECT ;

SELECT * FROM JOB_HISTORY WHERE JOB_ID = 24590 ;

SELECT * FROM JOB_HISTORY_INFO WHERE JOB_HISTORY_ID = 24600 ;

SELECT * FROM JOB_HISTORY_INFO WHERE JOB_HISTORY_ID = 24640 ;

SELECT * FROM JOB_HISTORY_INFO WHERE JOB_HISTORY_ID = 24670 ;

SELECT * FROM JOB_HISTORY_INFO WHERE JOB_HISTORY_ID = 24700 ;

SELECT * FROM JOB_HISTORY,JOB_HISTORY_INFO WHERE JOB_ID = 24590 
	AND JOB_HISTORY.JOB_HISTORY_ID IN (SELECT JOB_HISTORY_INFO.JOB_HISTORY_ID FROM JOB_HISTORY_INFO) 
	AND JOB_HISTORY.JOB_HISTORY_ID = JOB_HISTORY_INFO.JOB_HISTORY_ID AND COMMENT NOT LIKE ''  
	AND JOB_HISTORY_INFO.COMMENT NOT LIKE '%Old Task%' AND JOB_HISTORY_INFO.COMMENT NOT LIKE '%timer%'  
	ORDER BY  JOB_HISTORY.ACTION_DATE DESC

SELECT * FROM  JOB WHERE PROJECT_ID=  24590 AND NAME NOT LIKE 'Job for' ORDER BY NAME 

SELECT JOB_HISTORY.JOB_HISTORY_ID,
			 JOB_HISTORY_INFO.JOB_HISTORY_INFO_I, 
			 JOB_HISTORY_INFO.COMMENT,  
			 JOB_HISTORY.ACTION_DATE   
		FROM JOB_HISTORY_INFO,  
			 JOB_HISTORY WHERE   
			 JOB_HISTORY_INFO.JOB_HISTORY_ID  
		   IN (SELECT JOB_HISTORY_ID FROM   
			 JOB_HISTORY WHERE   
			 JOB_HISTORY.JOB_HISTORY_ID IN (SELECT  JOB_HISTORY.JOB_HISTORY_I FROM  JOB_HISTORY  WHERE JOB_ID = {JOB_ID} ))  
			 AND  JOB_HISTORY.JOB_HISTORY_ID =  JOB_HISTORY_INFO.JOB_HISTORY_ID AND  JOB_HISTORY_INFO.COMMENT NOT LIKE ''  
			 AND  JOB_HISTORY_INFO.COMMENT NOT LIKE '%Old Task%' AND  JOB_HISTORY_INFO.COMMENT NOT LIKE '%timer%'  
			 ORDER BY  JOB_HISTORY.ACTION_DATE DESC
