SELECT ASSET.* FROM ASSET WHERE ASSET_PRICE > 0
				AND ASSET_PRICE < 210 AND ASSET_DESC LIKE '%Cèdre%' AND IS_AVAILABLE=1 
			    AND ASSET_SID 
			    IN (SELECT ASSET_SID FROM ITEM WHERE ITEM.SID 
			    IN (SELECT ITEM_BUNDLE_ASS.ITEM_SID FROM ITEM_BUNDLE_ASS WHERE ITEM_BUNDLE_SID =5) ) ;
			    
			    
			    
			    
			    SELECT ASSET.* FROM ASSET WHERE ASSET_DESC LIKE '%Cèdre%' AND IS_AVAILABLE=1 
			    AND ASSET_SID 
			    IN (SELECT ASSET_SID FROM ITEM WHERE ITEM.SID 
			    IN (SELECT ITEM_BUNDLE_ASS.ITEM_SID FROM ITEM_BUNDLE_ASS WHERE ITEM_BUNDLE_SID =5) ) ;
			    
			    
			    
			    SELECT ASSET.* FROM ASSET, ADDRESS WHERE IS_AVAILABLE=1 
			  AND ASSET.ASSET_ADDRESS_ID = ADDRESS.ADDRESS_ID AND UPPER(ADDRESS.ZIPCITY) LIKE UPPER('%Ho%') 
			  AND ASSET_SID IN (SELECT ASSET_SID FROM ITEM WHERE ITEM.SID IN 
			  (SELECT ITEM_BUNDLE_ASS.ITEM_SID FROM ITEM_BUNDLE_ASS WHERE 
			  ITEM_BUNDLE_SID =5) ) ;
			  
			  
			  SELECT ASSET.* FROM ASSET,ADDRESS WHERE ASSET_PRICE > 0
				AND ASSET_PRICE < 250 AND ASSET_DESC LIKE '%Lon%' AND IS_AVAILABLE=1
				 AND ASSET.ASSET_ADDRESS_ID = ADDRESS.ADDRESS_ID AND UPPER(ADDRESS.ZIPCITY) LIKE UPPER('%Ho%') 
			    AND ASSET_SID 
			    IN (SELECT ASSET_SID FROM ITEM WHERE ITEM.SID 
			    IN (SELECT ITEM_BUNDLE_ASS.ITEM_SID FROM ITEM_BUNDLE_ASS WHERE ITEM_BUNDLE_SID =5) ) ;
			    
			    
SELECT * FROM ITEM_BUNDLE ;
    