SELECT * FROM ITEM WHERE  SID = 1 ;
SELECT * FROM ITEM WHERE  SID = 2 ;

SELECT COUNT(*) AS TEAM_COUNTS_ITEM_ALL FROM EVENT WHERE DIFFUSION_ID = 1 AND EVENT_TYPE_ID = 1 ;
SELECT COUNT(*) AS ADMIN_COUNTS_ITEM_ALL FROM EVENT WHERE DIFFUSION_ID <> 1 AND EVENT_TYPE_ID = 1;

SELECT COUNT(*) AS ADMIN_COUNT_ITEM_WEB FROM EVENT WHERE DIFFUSION_ID <> 1 AND EVENT_TYPE_ID = 1 AND ITEM_SID = 1;
SELECT COUNT(*) AS ADMIN_COUNT_ITEM_WAP FROM EVENT WHERE DIFFUSION_ID <> 1 AND EVENT_TYPE_ID = 1 AND ITEM_SID = 2;

SELECT COUNT(*) AS TEAM_COUNT_ITEM_WEB FROM EVENT WHERE DIFFUSION_ID = 1 AND EVENT_TYPE_ID = 1 AND ITEM_SID = 1;
SELECT COUNT(*) AS TEAM_COUNT_ITEM_WAP FROM EVENT WHERE DIFFUSION_ID = 1 AND EVENT_TYPE_ID = 1 AND ITEM_SID = 2;
