SELECT * FROM PROJECT,PROJECT_INFO,PROJECT_MEMBER_ASS 
	WHERE PROJECT_ID IN (SELECT PROJECT_ID_MBR_ASS FROM PROJECT_MEMBER_ASS WHERE MEMBER_ID = 1 ) 
	AND PROJECT_ID_INFO IN (SELECT PROJECT_ID FROM PROJECT) 
	AND PROJECT_ID_MBR_ASS =  PROJECT_ID
	AND PROJECT_ID_INFO=PROJECT_ID ORDER BY START_DATE DESC
