SELECT EVENT.EVENT_DATE ,DIFFUSION.NAME  FROM EVENT,DIFFUSION  WHERE  
	EVENT.EVENT_TYPE_ID = (SELECT EVENT_TYPE.ID FROM EVENT_TYPE WHERE EVENT_TYPE.NAME = 'diffusion_CREATEd')
								AND EVENT.DIFFUSION_ID= DIFFUSION.ID ORDER BY EVENT.EVENT_DATE ;

SELECT EVENT.SID, ITEM_DIFFUSED.TOKEN ,ITEM_DIFFUSED.DIFFUSED_TYPE_SID,  
			   ITEM_DIFFUSED.SENDER_ID, ITEM_DIFFUSED.RECEIVER_ID ,  
			   DIFFUSION.ID , DIFFUSION.MEMBER_ID,EVENT.EVENT_DATE,  
			   DIFFUSION.NAME FROM  EVENT,ITEM_DIFFUSED,DIFFUSION  
			   WHERE EVENT.DIFFUSION_ID= 3
			   AND EVENT.ITEM_DIFFUSED_SID = ITEM_DIFFUSED.SID  
			   AND DIFFUSION.ID = EVENT.DIFFUSION_ID  
			   AND EVENT.EVENT_TYPE_ID = 
			   (SELECT EVENT_TYPE.ID FROM EVENT_TYPE  WHERE EVENT_TYPE.NAME = 'item_CREATEd' )  
			   ORDER BY EVENT.EVENT_DATE ;			   
			   
SELECT EVENT.SID, ITEM_DIFFUSED.TOKEN ,ITEM_DIFFUSED.DIFFUSED_TYPE_SID,  
			   ITEM_DIFFUSED.SENDER_ID, ITEM_DIFFUSED.RECEIVER_ID ,  
			   DIFFUSION.ID ,EVENT.EVENT_DATE,  
			   DIFFUSION.NAME FROM  EVENT,ITEM_DIFFUSED,DIFFUSION  
			   WHERE EVENT.DIFFUSION_ID= 3 
				   AND EVENT.ITEM_DIFFUSED_SID = ITEM_DIFFUSED.SID  
				   AND DIFFUSION.ID=EVENT.DIFFUSION_ID  
				   AND EVENT.EVENT_TYPE_ID = 
					   (SELECT EVENT_TYPE.ID FROM EVENT_TYPE  WHERE EVENT_TYPE.NAME = 'item_CREATEd' )   
							   ORDER BY EVENT.EVENT_DATE ;

SELECT ITEM_SID FROM ITEM_BUNDLE_ASS 
		WHERE ITEM_BUNDLE_SID = 5  AND ITEM_SID = (SELECT SID FROM ITEM WHERE DISPLAY_NAME='model1' );
