SELECT COUNT(*) FROM ITEM_DIFFUSED 
	WHERE DIFFUSED_TYPE_SID = (SELECT SID FROM ITEM_DIFFUSED_TYPE WHERE NAME='WAP');

SELECT COUNT(*) FROM ITEM_DIFFUSED 
	WHERE DIFFUSED_TYPE_SID = (SELECT SID FROM ITEM_DIFFUSED_TYPE WHERE NAME='WEB');

SELECT COUNT(*) FROM  ITEM_DIFFUSED ;
