SELECT *  FROM DIFFUSION ;

SELECT *  FROM EVENT WHERE DIFFUSION_ID = 3 AND EVENT_TYPE_ID = 7;
		  
SELECT *  FROM EVENT_TYPE ;			  
SELECT *  FROM EVENT WHERE DIFFUSION_ID = 3 AND EVENT_TYPE_ID IN(7,8,9);
SELECT *  FROM EVENT WHERE DIFFUSION_ID = 3 AND EVENT_TYPE_ID = 3;

SELECT *  FROM EVENT WHERE DIFFUSION_ID = 3 ;

SELECT *  FROM EVENT WHERE DIFFUSION_ID = 3 AND EVENT_TYPE_ID IN(7,8,9);

SELECT EVENT.SID,EVENT.EVENT_TYPE_ID, ITEM_DIFFUSED.TOKEN,EVENT.MESSAGE,
			  ITEM_DIFFUSED.DIFFUSED_TYPE_SID, ITEM_DIFFUSED.SENDER_ID, 
			  ITEM_DIFFUSED.RECEIVER_ID ,DIFFUSION.ID ,EVENT.EVENT_DATE, 
			  DIFFUSION.NAME 
			  FROM  EVENT,ITEM_DIFFUSED,DIFFUSION 
			  WHERE EVENT.DIFFUSION_ID= 3
			  AND EVENT.ITEM_DIFFUSED_SID = ITEM_DIFFUSED.SID   
			  AND DIFFUSION.ID=EVENT.DIFFUSION_ID 
			  AND EVENT_TYPE_ID IN(7,8,9)
			  ORDER BY EVENT.EVENT_DATE;			

SELECT COMPANY.* FROM COMPANY,MEMBER WHERE  EMAIL ='eric.charles@u-mangate.be' 
	AND MEMBER.COMPANY_ID = COMPANY.COMPANY_ID  AND MEMBER.COMMUNITY_ID =1 ;

SELECT * FROM MEMBER ;

SELECT COUNT(*) FROM EVENT WHERE 
	EVENT_TYPE_ID = 7 
		AND DIFFUSION_ID=2
		AND YEAR(EVENT_DATE)= 2006
		AND DAY(EVENT_DATE)= 28    
		AND MONTH(EVENT_DATE)=4 ;

SELECT MAX(EVENT_DATE) FROM EVENT WHERE DIFFUSION_ID=2;
SELECT MAX(EVENT_DATE) FROM EVENT WHERE DIFFUSION_ID=1;

SELECT *  FROM EVENT WHERE EVENT_TYPE_ID= 8 AND DIFFUSION_ID=2 AND ITEM_DIFFUSED_SID=5 ORDER BY EVENT_DATE;

SELECT *  FROM ITEM ;

SELECT *  FROM ITEM_bundle ;
			  