SELECT REAL_NUMBER FROM	 TELEPHONE,COMPANY,MEMBER WHERE MEMBER.MEMBER_ID =10
AND MEMBER.COMPANY_ID = (SELECT COMPANY.COMPANY_ID FROM COMPANY WHERE COMPANY_ID =MEMBER.COMPANY_ID)    
AND COMPANY.COMPANY_ID =MEMBER.COMPANY_ID 
AND MEMBER.COMPANY_ID = (SELECT TELEPHONE.COMPANY_ID FROM TELEPHONE  WHERE TELEPHONE.COMPANY_ID=MEMBER.COMPANY_ID AND TYPE = '03_tel_funk' AND REAL_NUMBER=NUMBER AND  REAL_NUMBER!='(null)'	AND  REAL_NUMBER!='')
AND TELEPHONE.COMPANY_ID=MEMBER.COMPANY_ID
AND TELEPHONE.TYPE='03_tel_funk'
;
SELECT REAL_NUMBER FROM	 TELEPHONE,COMPANY,MEMBER WHERE MEMBER.MEMBER_ID =825790
AND MEMBER.COMPANY_ID = (SELECT COMPANY.COMPANY_ID FROM COMPANY WHERE COMPANY_ID =MEMBER.COMPANY_ID)    
AND COMPANY.COMPANY_ID =MEMBER.COMPANY_ID 
AND MEMBER.COMPANY_ID = (SELECT TELEPHONE.COMPANY_ID FROM TELEPHONE  WHERE TELEPHONE.COMPANY_ID=MEMBER.COMPANY_ID AND TYPE = '03_tel_funk' AND REAL_NUMBER=NUMBER AND  REAL_NUMBER!='(null)'	AND  REAL_NUMBER!='')
AND TELEPHONE.COMPANY_ID=MEMBER.COMPANY_ID
AND TELEPHONE.TYPE='03_tel_funk'
