SELECT ITEM_BUNDLE.*, 
			  ITEM_BUNDLE_TYPE.NAME   itemBundleTypeName,
			  ITEM_BUNDLE_TYPE.DESCRIPTION itemBundleTypeDescription, 
			  ITEM_BUNDLE_I18N.LANGUAGE_SID itemBundleI18NLanguageSid, 
			  ITEM_BUNDLE_I18N.KEYWORDS itemBundleI18NKeywords, 
			  ITEM_BUNDLE_I18N.MESSAGE itemBundleI18NMessage, 
			  ITEM_BUNDLE_I18N.TITLE itemBundleI18NTitle, 
			  ITEM_BUNDLE_I18N.SID_ITB_I18N itemBundleI18NSid, 
			  SKIN.NAME itemBundleSkinName , 
			  ITEM_BUNDLE_TYPE.NAME itemBundleTypeName, 
			  ITEM_BUNDLE_TYPE.DESCRIPTION itemBundleTypeDescriptiON 
			  FROM ITEM_BUNDLE , ITEM_BUNDLE_TYPE, SKIN , ITEM_BUNDLE_I18N 
			  WHERE ITEM_BUNDLE_I18N.ITEM_BUNDLE_SID = ITEM_BUNDLE.SID 
			  AND ITEM_BUNDLE.SKIN_SID =  SKIN.SID 
			  AND ITEM_BUNDLE_I18N.LANGUAGE_SID = 34 
			  AND ITEM_BUNDLE.SERVER_NAME ='www.angi.be' 
			  AND ITEM_BUNDLE_TYPE.SID = 1
			  ;
			  
			  
SELECT ITEM.*, ITEM_I18N.*
 FROM ITEM, ITEM_BUNDLE_ASS, ITEM_BUNDLE ,ITEM_I18N 
			  WHERE ITEM.SID = ITEM_BUNDLE_ASS.ITEM_SID 
			  AND  ITEM.SID = ITEM_I18N.ITEM_SID    
			  AND  ITEM_BUNDLE.SID = ITEM_BUNDLE_ASS.ITEM_BUNDLE_SID 
			  AND  ITEM_I18N.LANGUAGE_SID = 34
			  AND ITEM_BUNDLE.SERVER_NAME = 'www.angi.be' AND ITEM.PATH = '' 
			  AND ITEM.DISPLAY_NAME = 'index' AND ITEM.EXTENSION = 'html';
			  
			  
			  
			  
			  
			  
SELECT ITEM_BUNDLE.*, 
			  ITEM_BUNDLE_TYPE.NAME   itemBundleTypeName, 
			  ITEM_BUNDLE_TYPE.DESCRIPTION itemBundleTypeDescription, 
			  ITEM_BUNDLE_I18N.LANGUAGE_SID itemBundleI18NLanguageSid,
			  ITEM_BUNDLE_I18N.KEYWORDS itemBundleI18NKeywords,
			  ITEM_BUNDLE_I18N.MESSAGE itemBundleI18NMessage,
			  ITEM_BUNDLE_I18N.TITLE itemBundleI18NTitle,
			  ITEM_BUNDLE_I18N.SID_ITB_I18N itemBundleI18NSid,
			  SKIN.NAME itemBundleSkinName 
			  FROM ITEM_BUNDLE ,ITEM_BUNDLE_TYPE,ITEM_BUNDLE_I18N,SKIN 
			  WHERE ITEM_BUNDLE.SID = 11
			  AND ITEM_BUNDLE_I18N.ITEM_BUNDLE_SID = ITEM_BUNDLE.SID 
			  AND ITEM_BUNDLE.SKIN_SID =  SKIN.SID 	
			  AND ITEM_BUNDLE.ITEM_BUNDLE_TY_SID = ITEM_BUNDLE_TYPE.SID 		  
			  
			  ;
			  
SELECT *  FROM ITEM_BUNDLE ;	





SELECT ITEM_BUNDLE.*, 
			  ITEM_BUNDLE_TYPE.NAME itemBundleTypeName, 
			  ITEM_BUNDLE_TYPE.DESCRIPTION itemBundleTypeDescription, 
			  ITEM_BUNDLE_I18N.LANGUAGE_SID itemBundleI18NLanguageSid,
			  ITEM_BUNDLE_I18N.KEYWORDS itemBundleI18NKeywords,
			  ITEM_BUNDLE_I18N.MESSAGE itemBundleI18NMessage,
			  ITEM_BUNDLE_I18N.TITLE itemBundleI18NTitle,
			  ITEM_BUNDLE_I18N.SID_ITB_I18N itemBundleI18NSid,
			  SKIN.NAME itemBundleSkinName 
			  FROM ITEM_BUNDLE ,ITEM_BUNDLE_TYPE,ITEM_BUNDLE_I18N,SKIN 
			  WHERE ITEM_BUNDLE_I18N.ITEM_BUNDLE_SID = ITEM_BUNDLE.SID
			  AND ITEM_BUNDLE.SKIN_SID = SKIN.SID   
			  AND ITEM_BUNDLE.ITEM_BUNDLE_TY_SID = ITEM_BUNDLE_TYPE.SID 			  
			  AND ITEM_BUNDLE.SID = 2
			  AND ITEM_BUNDLE_I18N.ITEM_BUNDLE_SID =2 ;




		  
			  
			  			  