ALTER TABLE JOB_HISTORY
	ADD CONSTRAINT PK_JOB_HISTORY PRIMARY KEY (
		JOB_HISTORY_ID
		)
;

ALTER TABLE OBJ_PROPERTY
	ADD CONSTRAINT PK_OBJ_PROPERTY PRIMARY KEY (
		OBJ_PROPERTY_ID
		)
;

ALTER TABLE DATE_INFO
	ADD CONSTRAINT PK_DATE_INFO PRIMARY KEY (
		DATE_INFO_ID
		)
;

ALTER TABLE COMPANY_ASSIGNMENT
	ADD CONSTRAINT PK_COMP_ASS PRIMARY KEY (
		COMPANY_ASSIGNMENT
		)
;

ALTER TABLE SECU_ROLE
	ADD CONSTRAINT PK_SECU_ROLE PRIMARY KEY (
		ID
		)
;

ALTER TABLE DATE_X
	ADD CONSTRAINT PK_DATE_X PRIMARY KEY (
		DATE_ID
		)
;

ALTER TABLE NEWS_ARTICLE
	ADD CONSTRAINT PK_NEWS_ARTICLE PRIMARY KEY (
		NEWS_ARTICLE_ID
		)
;

ALTER TABLE INVOICE_ARTICLE_AS
	ADD CONSTRAINT PK_INV_ART_AS PRIMARY KEY (
		INVOICE_ARTICLE_AS_ID
		)
;

ALTER TABLE TABLE_VERSION
	ADD CONSTRAINT PK_TABLE_VERSION PRIMARY KEY (
		TABLE_NAME
		)
;

ALTER TABLE LOG
	ADD CONSTRAINT PK_LOG PRIMARY KEY (
		LOG_ID
		)
;

ALTER TABLE COMPANY_VALUE
	ADD CONSTRAINT PK_COMP_VALUE PRIMARY KEY (
		COMPANY_VALUE_ID
		)
;

ALTER TABLE RESOURCE
	ADD CONSTRAINT PK_RESOURCE_ID PRIMARY KEY (
		RESOURCE_ID
		)
;

ALTER TABLE INVOICE_ACCOUNTING
	ADD CONSTRAINT PK_INV_ACCOUNTING PRIMARY KEY (
		INVOICE_ACCOUNTING
		)
;

ALTER TABLE STAFF
	ADD CONSTRAINT PK_STAFF PRIMARY KEY (
		STAFF_ID
		)
;

ALTER TABLE DIFFUSION
	ADD CONSTRAINT PK_AOS_NEWS_CMPG PRIMARY KEY (
		ID
		)
;

ALTER TABLE URL
	ADD CONSTRAINT PK_URL PRIMARY KEY (
		URL_ID
		)
;

ALTER TABLE DOCUMENT_EDITING
	ADD CONSTRAINT PK_DOC_EDITING PRIMARY KEY (
		DOCUMENT_EDITING_I
		)
;

ALTER TABLE PRES_CONS
	ADD CONSTRAINT PRE_Constraint1 PRIMARY KEY (
		ID
		)
;

ALTER TABLE ITEM_DIFFUSED
	ADD CONSTRAINT ITEDIFF_PK PRIMARY KEY (
		SID
		)
;

ALTER TABLE COMMUNITY_TYPE
	ADD CONSTRAINT COMMTYPE_1 PRIMARY KEY (
		ID
		)
;

ALTER TABLE INVOICE
	ADD CONSTRAINT PK_INVOICE PRIMARY KEY (
		INVOICE_ID
		)
;

ALTER TABLE SECU_PERM_URL
	ADD CONSTRAINT PK_SEC_PERM PRIMARY KEY (
		ID
		)
;

ALTER TABLE EVENT
	ADD CONSTRAINT PK_AOS_NEWS_EV PRIMARY KEY (
		SID
		)
;

ALTER TABLE COMPANY_INFO
	ADD CONSTRAINT PK_COMP_INFO PRIMARY KEY (
		COMPANY_INFO_ID
		)
;

ALTER TABLE ITEM_BUNDLE_TYPE
	ADD CONSTRAINT ITBDLTYP_PK PRIMARY KEY (
		SID
		)
;

ALTER TABLE ARTICLE_CATEGORY
	ADD CONSTRAINT PK_ART_CAT_ID PRIMARY KEY (
		ARTICLE_CATEGORY_I
		)
;

ALTER TABLE JOB_HISTORY_INFO
	ADD CONSTRAINT PK_JOB_HIST_INF_1 PRIMARY KEY (
		JOB_HISTORY_INFO_I
		)
;

ALTER TABLE TELEPHONE
	ADD CONSTRAINT PK_TELEPHONE PRIMARY KEY (
		TELEPHONE_ID
		)
;

ALTER TABLE DOCUMENT_VERSION
	ADD CONSTRAINT PK_DOC_VERSION PRIMARY KEY (
		DOCUMENT_VERSION_I
		)
;

ALTER TABLE URL_CRITERION
	ADD CONSTRAINT PK_CRITERION PRIMARY KEY (
		CRITERION_ID
		)
;

ALTER TABLE MEMBER
	ADD CONSTRAINT MEMB_PK PRIMARY KEY (
		MEMBER_ID
		)
;

ALTER TABLE JOB_ASSIGNMENT
	ADD CONSTRAINT PK_JOB_ASSIGNMENT PRIMARY KEY (
		JOB_ASSIGNMENT_ID
		)
;

ALTER TABLE INVOICE_ACTION
	ADD CONSTRAINT PK_INV_ACTION PRIMARY KEY (
		INVOICE_ACTION_ID
		)
;

ALTER TABLE PROJECT
	ADD CONSTRAINT PK_PROJECT PRIMARY KEY (
		PROJECT_ID
		)
;

ALTER TABLE EVENT_TYPE
	ADD CONSTRAINT PK_AOS_NEWS_EV_TYPE PRIMARY KEY (
		ID
		)
;

ALTER TABLE SESSION_LOG
	ADD CONSTRAINT PK_SESSION_LOG PRIMARY KEY (
		SESSION_LOG_ID
		)
;

ALTER TABLE ROLE
	ADD CONSTRAINT PK_AOS_ROLE_ID PRIMARY KEY (
		ROLE_ID
		)
;

ALTER TABLE STATUS_TYPE
	ADD CONSTRAINT NEW_Constraint1 PRIMARY KEY (
		SID
		)
;

ALTER TABLE APPOINTMENT_RESOUR
	ADD CONSTRAINT PK_APP_RES_ID PRIMARY KEY (
		APPOINTMENT_RES_ID
		)
;

ALTER TABLE NEWS_ARTICLE_LINK
	ADD CONSTRAINT PK_ARTICLE_LINK PRIMARY KEY (
		NEWS_ARTICLE_LINK_
		)
;

ALTER TABLE INVOICE_ACCOUNT
	ADD CONSTRAINT PK_INV_ACCOUNT PRIMARY KEY (
		INVOICE_ACCOUNT_ID
		)
;

ALTER TABLE SECU_PERM
	ADD CONSTRAINT PK_SECU_PREM PRIMARY KEY (
		SID
		)
;

ALTER TABLE OBJECT_ACL
	ADD CONSTRAINT PK_OBJ_ACL PRIMARY KEY (
		OBJECT_ACL_ID
		)
;

ALTER TABLE ARTICLE
	ADD CONSTRAINT PK_ARTICLE PRIMARY KEY (
		ARTICLE_ID
		)
;

ALTER TABLE JOB
	ADD CONSTRAINT PK_JOB PRIMARY KEY (
		JOB_ID
		)
;

ALTER TABLE ARTICLE_UNIT
	ADD CONSTRAINT PK_ART_UNIT PRIMARY KEY (
		ARTICLE_UNIT_ID
		)
;

ALTER TABLE COMMUNITY
	ADD CONSTRAINT PK_AOS_COMMU_ID PRIMARY KEY (
		COMMUNITY_ID
		)
;

ALTER TABLE OBJ_INFO
	ADD CONSTRAINT PK_OBJ_INFO PRIMARY KEY (
		OBJ_ID
		)
;

ALTER TABLE DATE_COMPANY_ASSIG
	ADD CONSTRAINT PK_DATE_COMP_ASSIG PRIMARY KEY (
		DATE_COMPANY_ASSIG
		)
;

ALTER TABLE PROJECT_INFO
	ADD CONSTRAINT PK_PROJECT_INFO PRIMARY KEY (
		PROJECT_INFO_ID
		)
;

ALTER TABLE PROJECT_COMPANY_AS
	ADD CONSTRAINT PK_PRJ_COMP_ASS PRIMARY KEY (
		PROJECT_COMPANY_AS
		)
;

ALTER TABLE ADDRESS
	ADD CONSTRAINT PK_ADDRESS PRIMARY KEY (
		ADDRESS_ID
		)
;

ALTER TABLE COMPANY
	ADD CONSTRAINT PK_COMP_ID PRIMARY KEY (
		COMPANY_ID
		)
;

ALTER TABLE DOCUMENT
	ADD CONSTRAINT PK_DOCUMENT PRIMARY KEY (
		DOCUMENT_ID
		)
;

ALTER TABLE COMPANY_CATEGORY
	ADD CONSTRAINT PK_COMP_CAT PRIMARY KEY (
		COMPANY_CATEGORY_I
		)
;

ALTER TABLE SECU_COMPANY_ROLE
	ADD CONSTRAINT PK_SEC_COMP_ROLE PRIMARY KEY (
		SECU_ROLE_ID
		)
;

ALTER TABLE SECU_COMPANY_PERM
	ADD CONSTRAINT PK_SECU_CMP PRIMARY KEY (
		SID
		)
;

ALTER TABLE JOB_RESOURCE_ASSIG
	ADD CONSTRAINT PK_JOB_RESOURCE PRIMARY KEY (
		JOB_RESOURCE_ASSIG
		)
;

ALTER TABLE OBJ_LINK
	ADD CONSTRAINT PK_OBJ_LINK PRIMARY KEY (
		OBJ_LINK_ID
		)
;

ALTER TABLE KEYWORD
	ADD CONSTRAINT KEY_PK PRIMARY KEY (
		SID
		)
;

ALTER TABLE ITEM_BUNDLE
	ADD CONSTRAINT ITEBUN_PK PRIMARY KEY (
		SID
		)
;

ALTER TABLE ITEM_DIFFUSED_TYPE
	ADD CONSTRAINT Constraint1 PRIMARY KEY (
		SID
		)
;

ALTER TABLE DOWNLOAD_NUMBER
	ADD CONSTRAINT DOW_Constraint1 PRIMARY KEY (
		SID
		)
;

ALTER TABLE SKIN
	ADD CONSTRAINT SKIN_PK PRIMARY KEY (
		SID
		)
;

ALTER TABLE ITEM_TYPE
	ADD CONSTRAINT ITETY_PK PRIMARY KEY (
		SID
		)
;

ALTER TABLE ITEM
	ADD CONSTRAINT Constraint2 PRIMARY KEY (
		SID
		)
;

ALTER TABLE SKIN_TYPE
	ADD CONSTRAINT SKINTYPE_PK PRIMARY KEY (
		SID
		)
;

ALTER TABLE ITEM_BUNDLE_ASS
	ADD CONSTRAINT ITEBDASS_PK PRIMARY KEY (
		SID
		)
;

ALTER TABLE JOB_HISTORY
	ADD CONSTRAINT FK_JOB_HISTORY_1 FOREIGN KEY (
		JOB_ID
		)
	REFERENCES JOB (
		JOB_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE DATE_INFO
	ADD CONSTRAINT FK_DATE_INFO_1 FOREIGN KEY (
		DATE_ID
		)
	REFERENCES DATE_X (
		DATE_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE COMPANY_ASSIGNMENT
	ADD CONSTRAINT COM_Constraint1 FOREIGN KEY (
		COMPANY_ID
		)
	REFERENCES COMPANY (
		COMPANY_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE COMPANY_ASSIGNMENT
	ADD CONSTRAINT COM_Constraint2 FOREIGN KEY (
		SUB_COMPANY_ID
		)
	REFERENCES COMPANY (
		COMPANY_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE DATE_X
	ADD CONSTRAINT FK_DATE_X_2 FOREIGN KEY (
		PARENT_DATE_ID
		)
	REFERENCES DATE_X (
		DATE_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE COMPANY_VALUE
	ADD CONSTRAINT COM_Constraint5 FOREIGN KEY (
		COMPANY_ID
		)
	REFERENCES COMPANY (
		COMPANY_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE DIFFUSION
	ADD CONSTRAINT DIF_Constraint2 FOREIGN KEY (
		MEMBER_ID
		)
	REFERENCES MEMBER (
		MEMBER_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE DIFFUSION
	ADD CONSTRAINT DIF_Constraint1 FOREIGN KEY (
		STATUS_TYPE_ID
		)
	REFERENCES STATUS_TYPE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE DOCUMENT_EDITING
	ADD CONSTRAINT FK_DOC_EDITING_2 FOREIGN KEY (
		DOCUMENT_ID
		)
	REFERENCES DOCUMENT (
		DOCUMENT_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM_DIFFUSED
	ADD CONSTRAINT ITE_Constraint3 FOREIGN KEY (
		DIFFUSED_TYPE_SID
		)
	REFERENCES ITEM_DIFFUSED_TYPE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM_DIFFUSED
	ADD CONSTRAINT ITE_DIF1 FOREIGN KEY (
		SENDER_ID
		)
	REFERENCES MEMBER (
		MEMBER_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM_DIFFUSED
	ADD CONSTRAINT ITE_Constraint2 FOREIGN KEY (
		RECEIVER_ID
		)
	REFERENCES MEMBER (
		MEMBER_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM_DIFFUSED
	ADD CONSTRAINT ITE_Constraint1 FOREIGN KEY (
		ITEM_SID
		)
	REFERENCES ITEM (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE EVENT
	ADD CONSTRAINT NEWS_EVENT_7 FOREIGN KEY (
		EVENT_TYPE_ID
		)
	REFERENCES EVENT_TYPE (
		ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE EVENT
	ADD CONSTRAINT EVE_Constraint6 FOREIGN KEY (
		DIFFUSION_ID
		)
	REFERENCES DIFFUSION (
		ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE EVENT
	ADD CONSTRAINT EVE_Constraint5 FOREIGN KEY (
		MEMBER_ID
		)
	REFERENCES MEMBER (
		MEMBER_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE EVENT
	ADD CONSTRAINT EVE_Constraint4 FOREIGN KEY (
		ITEM_BUNDLE_SID
		)
	REFERENCES ITEM_BUNDLE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE EVENT
	ADD CONSTRAINT EVE_Constraint3 FOREIGN KEY (
		ITEM_SID
		)
	REFERENCES ITEM (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE EVENT
	ADD CONSTRAINT EVE_Constraint1 FOREIGN KEY (
		ITEM_DIFFUSED_SID
		)
	REFERENCES ITEM_DIFFUSED (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE COMPANY_INFO
	ADD CONSTRAINT COM_Constraint6 FOREIGN KEY (
		COMPANY_ID
		)
	REFERENCES COMPANY (
		COMPANY_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE JOB_HISTORY_INFO
	ADD CONSTRAINT FK_JOB_HIST_INF_1 FOREIGN KEY (
		JOB_HISTORY_ID
		)
	REFERENCES JOB_HISTORY (
		JOB_HISTORY_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE TELEPHONE
	ADD CONSTRAINT TEL_Constraint1 FOREIGN KEY (
		COMPANY_ID
		)
	REFERENCES COMPANY (
		COMPANY_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE DOCUMENT_VERSION
	ADD CONSTRAINT FK_DOC_VERSION_2 FOREIGN KEY (
		DOCUMENT_ID
		)
	REFERENCES DOCUMENT (
		DOCUMENT_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE MEMBER
	ADD CONSTRAINT MEM_Constraint1 FOREIGN KEY (
		COMPANY_ID
		)
	REFERENCES COMPANY (
		COMPANY_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE MEMBER
	ADD CONSTRAINT MEMB_C FOREIGN KEY (
		ROLE_ID
		)
	REFERENCES ROLE (
		ROLE_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE MEMBER
	ADD CONSTRAINT MEMB_B FOREIGN KEY (
		COMMUNITY_ID
		)
	REFERENCES COMMUNITY (
		COMMUNITY_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE JOB_ASSIGNMENT
	ADD CONSTRAINT FK_JOB_ASS_2 FOREIGN KEY (
		PARENT_JOB_ID
		)
	REFERENCES JOB (
		JOB_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE JOB_ASSIGNMENT
	ADD CONSTRAINT FK_JOB_ASS_1 FOREIGN KEY (
		CHILD_JOB_ID
		)
	REFERENCES JOB (
		JOB_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE SECU_PERM
	ADD CONSTRAINT FK_SECU_PERM_2 FOREIGN KEY (
		ROLE_ID
		)
	REFERENCES SECU_ROLE (
		ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE SECU_PERM
	ADD CONSTRAINT FK_SECU_PERM_1 FOREIGN KEY (
		PERM_ID
		)
	REFERENCES SECU_PERM_URL (
		ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE JOB
	ADD CONSTRAINT FK_JOB_4 FOREIGN KEY (
		PROJECT_ID
		)
	REFERENCES PROJECT (
		PROJECT_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE JOB
	ADD CONSTRAINT FK_JOB_3 FOREIGN KEY (
		PARENT_JOB_ID
		)
	REFERENCES JOB (
		JOB_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE COMMUNITY
	ADD CONSTRAINT COMUNI_A1 FOREIGN KEY (
		COMMUNITY_TYPE_ID
		)
	REFERENCES COMMUNITY_TYPE (
		ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE DATE_COMPANY_ASSIG
	ADD CONSTRAINT FK_DATE_COMP_1 FOREIGN KEY (
		DATE_ID
		)
	REFERENCES DATE_X (
		DATE_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE PROJECT_INFO
	ADD CONSTRAINT FK_PROJECT_INFO_1 FOREIGN KEY (
		PROJECT_ID
		)
	REFERENCES PROJECT (
		PROJECT_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE PROJECT_COMPANY_AS
	ADD CONSTRAINT FK_PRJ_COMP_ASS_1 FOREIGN KEY (
		PROJECT_ID
		)
	REFERENCES PROJECT (
		PROJECT_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE PROJECT_COMPANY_AS
	ADD CONSTRAINT PRO_Constraint1 FOREIGN KEY (
		COMPANY_ID
		)
	REFERENCES COMPANY (
		COMPANY_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ADDRESS
	ADD CONSTRAINT ADD_Constraint1 FOREIGN KEY (
		COMPANY_ID
		)
	REFERENCES COMPANY (
		COMPANY_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE DOCUMENT
	ADD CONSTRAINT FK_DOCUMENT_5 FOREIGN KEY (
		PARENT_DOCUMENT_ID
		)
	REFERENCES DOCUMENT (
		DOCUMENT_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE DOCUMENT
	ADD CONSTRAINT FK_DOCUMENT_3 FOREIGN KEY (
		PROJECT_ID
		)
	REFERENCES PROJECT (
		PROJECT_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE DOCUMENT
	ADD CONSTRAINT FK_DOCUMENT_2 FOREIGN KEY (
		DATE_ID
		)
	REFERENCES DATE_X (
		DATE_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE SECU_COMPANY_ROLE
	ADD CONSTRAINT FK_SEC_COM_ROLE_1 FOREIGN KEY (
		ROLE_ID
		)
	REFERENCES SECU_ROLE (
		ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE SECU_COMPANY_ROLE
	ADD CONSTRAINT SEC_Constraint1 FOREIGN KEY (
		COMPANY_ID
		)
	REFERENCES COMPANY (
		COMPANY_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE SECU_COMPANY_PERM
	ADD CONSTRAINT SEC_Constraint7 FOREIGN KEY (
		COMPANY_ID
		)
	REFERENCES COMPANY (
		COMPANY_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE SECU_COMPANY_PERM
	ADD CONSTRAINT FK_SEC_COM_PRM_1 FOREIGN KEY (
		PERM_ID
		)
	REFERENCES SECU_PERM_URL (
		ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE JOB_RESOURCE_ASSIG
	ADD CONSTRAINT FK_JOB_RES_ASS_1 FOREIGN KEY (
		JOB_ID
		)
	REFERENCES JOB (
		JOB_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE JOB_RESOURCE_ASSIG
	ADD CONSTRAINT FK_JOB_RES_ASS_2 FOREIGN KEY (
		RESOURCE_ID
		)
	REFERENCES RESOURCE (
		RESOURCE_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE KEYWORD
	ADD CONSTRAINT KEY_Constraint1 FOREIGN KEY (
		ITEM_BUNDLE_SID
		)
	REFERENCES ITEM_BUNDLE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM_BUNDLE
	ADD CONSTRAINT ITE_Constraint9 FOREIGN KEY (
		MEMBER_ID
		)
	REFERENCES MEMBER (
		MEMBER_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM_BUNDLE
	ADD CONSTRAINT ITE_Constraint8 FOREIGN KEY (
		ITEM_BUNDLE_TY_SID
		)
	REFERENCES ITEM_BUNDLE_TYPE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM_BUNDLE
	ADD CONSTRAINT ITE_Constraint10 FOREIGN KEY (
		SKIN_SID
		)
	REFERENCES SKIN (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE SKIN
	ADD CONSTRAINT SKIN_1 FOREIGN KEY (
		SKIN_TYPE_SID
		)
	REFERENCES SKIN_TYPE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM
	ADD CONSTRAINT ITE_Constraint12 FOREIGN KEY (
		ITEM_TYPE_SID
		)
	REFERENCES ITEM_TYPE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM
	ADD CONSTRAINT ITE_Constraint11 FOREIGN KEY (
		STATUS_TYPE_SID
		)
	REFERENCES STATUS_TYPE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM_BUNDLE_ASS
	ADD CONSTRAINT ITE_Constraint14 FOREIGN KEY (
		ITEM_SID
		)
	REFERENCES ITEM (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM_BUNDLE_ASS
	ADD CONSTRAINT ITE_Constraint13 FOREIGN KEY (
		ITEM_BUNDLE_SID
		)
	REFERENCES ITEM_BUNDLE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;


