ALTER TABLE MAIL_ACCOUNT
	ADD CONSTRAINT MAIL_ACCOUNT_PK PRIMARY KEY (
		MAIL_ACCOUNT_SID
		)
;

ALTER TABLE ACCESS_CONTROL_TYPE
	ADD CONSTRAINT ACCESS_CONTROL_TYPE_PK PRIMARY KEY (
		ACCESS_CONTROL_TYPE_SID
		)
;

ALTER TABLE ACCESS_CONTROL
	ADD CONSTRAINT ACCESS_CONTROL_PK PRIMARY KEY (
		ACCESS_CONTROL_SID
		)
;

ALTER TABLE GROUP_TYPE
	ADD CONSTRAINT GROUP_TYPE_PK PRIMARY KEY (
		GROUP_TYPE_SID
		)
;

ALTER TABLE LINK
	ADD CONSTRAINT LINK_PK PRIMARY KEY (
		LINK_SID
		)
;

ALTER TABLE SCHEDULE_RESOURCE_ASSIG
	ADD CONSTRAINT SCHEDULE_RESOURCE_ASSIG_PK PRIMARY KEY (
		SCHEDULE_RESOURCE_ASSIG_SID
		)
;

ALTER TABLE TARGET
	ADD CONSTRAINT TARGET_PK PRIMARY KEY (
		TARGET_SID
		)
;

ALTER TABLE DELIVERABLE
	ADD CONSTRAINT DELIVERABLE_PK PRIMARY KEY (
		DELIVERABLE_SID
		)
;

ALTER TABLE ASSET_TYPE
	ADD CONSTRAINT ASSET_TYPE_PK PRIMARY KEY (
		ASSET_TYPE_SID
		)
;

ALTER TABLE GLOSSARY_TYPE
	ADD CONSTRAINT GLOSSARY_TYPE_PK PRIMARY KEY (
		GLOSSARY_TYPE_SID
		)
;

ALTER TABLE SKIN_TYPE
	ADD CONSTRAINT SKIN_TYPE_PK PRIMARY KEY (
		SKIN_TYPE_SID
		)
;

ALTER TABLE GLOSSARY
	ADD CONSTRAINT GLOSSARY_PK PRIMARY KEY (
		GLOSSARY_SID
		)
;

ALTER TABLE ASSET_ADDRESS
	ADD CONSTRAINT ASSET_ADDRESS_PK PRIMARY KEY (
		ASSET_ADDRESS_SID
		)
;

ALTER TABLE ITEM_BUNDLE_ASS
	ADD CONSTRAINT ITEM_BUNDLE_ASS_PK PRIMARY KEY (
		ITEM_BUNDLE_ASS_SID
		)
;

ALTER TABLE URL_PROPERTY
	ADD CONSTRAINT URL_PROPERTY_PK PRIMARY KEY (
		URL_PROPERTY_SID
		)
;

ALTER TABLE ASSET
	ADD CONSTRAINT ASSET_PK PRIMARY KEY (
		ASSET_SID
		)
;

ALTER TABLE PROJECT_TYPE
	ADD CONSTRAINT PROJECT_TYPE_PK PRIMARY KEY (
		PROJECT_TYPE_SID
		)
;

ALTER TABLE URL
	ADD CONSTRAINT URL_URL_SERVER_NAME_UN UNIQUE (
		URL_SERVER_NAME
		)
;

ALTER TABLE URL
	ADD CONSTRAINT URL_PK PRIMARY KEY (
		URL_SID
		)
;

ALTER TABLE ITEM_TYPE_TRANSF
	ADD CONSTRAINT ITEM_TYPE_TRANSF_PK PRIMARY KEY (
		ITEM_TYPE_TRANSF_SID
		)
;

ALTER TABLE INVOICE_TYPE
	ADD CONSTRAINT INVOICE_TYPE_PK PRIMARY KEY (
		INVOICE_TYPE_SID
		)
;

ALTER TABLE COMMUNITY_SKIN
	ADD CONSTRAINT COMMUNITY_SKIN_PK PRIMARY KEY (
		COMMUNITY_SKIN_SID
		)
;

ALTER TABLE IDENTITY_LANGUAGE
	ADD CONSTRAINT IDENTITY_LANGUAGE_PK PRIMARY KEY (
		IDENTITY_LANGUAGE_SID
		)
;

ALTER TABLE IDENTITY_TYPE
	ADD CONSTRAINT IDENTITY_TYPE_PK PRIMARY KEY (
		IDENTITY_TYPE_SID
		)
;

ALTER TABLE MAIL
	ADD CONSTRAINT MAIL_PK PRIMARY KEY (
		MAIL_SID
		)
;

ALTER TABLE ITEM_I18N
	ADD CONSTRAINT ITEM_I18N_PK PRIMARY KEY (
		ITEM_I18N_SID
		)
;

ALTER TABLE LANGUAGE
	ADD CONSTRAINT LANGUAGE_PK PRIMARY KEY (
		LANGUAGE_SID
		)
;

ALTER TABLE RELATION_TYPE
	ADD CONSTRAINT RELATION_TYPE_PK PRIMARY KEY (
		RELATION_TYPE_SID
		)
;

ALTER TABLE MAIL_IDENTITY_TYPE
	ADD CONSTRAINT MAIL_IDENTITY_TYPE_PK PRIMARY KEY (
		MAIL_IDENTITY_TYPE_SID
		)
;

ALTER TABLE LOCATION_SOURCE
	ADD CONSTRAINT LOCATION_SOURCE_PK PRIMARY KEY (
		LOCATION_SOURCE_SID
		)
;

ALTER TABLE MAIL_IDENTITY
	ADD CONSTRAINT MAIL_IDENTITY_PK PRIMARY KEY (
		MAIL_IDENTITY_SID
		)
;

ALTER TABLE ASSET_PHOTO
	ADD CONSTRAINT ASSET_PHOTO_PK PRIMARY KEY (
		ASSET_PHOTO_SID
		)
;

ALTER TABLE TIMEZONE
	ADD CONSTRAINT TIMEZONE_PK PRIMARY KEY (
		TIMEZONE_SID
		)
;

ALTER TABLE PROJECT_MEMBER
	ADD CONSTRAINT PROJECT_MEMBER_PK PRIMARY KEY (
		PROJECT_MEMBER_SID
		)
;

ALTER TABLE THREAD
	ADD CONSTRAINT THREAD_PK PRIMARY KEY (
		THREAD_SID
		)
;

ALTER TABLE TARGET_COMMENT
	ADD CONSTRAINT TARGET_COMMENT_PK PRIMARY KEY (
		TARGET_COMMENT_SID
		)
;

ALTER TABLE ITEM_BUNDLE
	ADD CONSTRAINT ITEM_BUNDLE_PK PRIMARY KEY (
		ITEM_BUNDLE_SID
		)
;

ALTER TABLE MAIL_ACCOUNT_TYPE
	ADD CONSTRAINT MAIL_ACCOUNT_TYPE_PK PRIMARY KEY (
		MAIL_ACCOUNT_TYPE_SID
		)
;

ALTER TABLE DELIVERABLE_COMMENT
	ADD CONSTRAINT DELIVERABLE_COMMENT_PK PRIMARY KEY (
		DELIVERABLE_COMMENT_SID
		)
;

ALTER TABLE MAIL_ATTACHMENT
	ADD CONSTRAINT MAIL_ATTACHMENT_PK PRIMARY KEY (
		MAIL_ATTACHMENT_SID
		)
;

ALTER TABLE ITEM
	ADD CONSTRAINT ITEM_PK PRIMARY KEY (
		ITEM_SID
		)
;

ALTER TABLE SCHEDULE_TYPE
	ADD CONSTRAINT SCHEDULE_TYPE_PK PRIMARY KEY (
		SCHEDULE_TYPE_SID
		)
;

ALTER TABLE COUNTRY
	ADD CONSTRAINT COUNTRY_PK PRIMARY KEY (
		COUNTRY_SID
		)
;

ALTER TABLE SKIN
	ADD CONSTRAINT SKIN_PK PRIMARY KEY (
		SKIN_SID
		)
;

ALTER TABLE ASSET_VALUE
	ADD CONSTRAINT ASSET_VALUE_PK PRIMARY KEY (
		ASSET_VALUE_SID
		)
;

ALTER TABLE MAIL_THREAD
	ADD CONSTRAINT MAIL_THREAD_PK PRIMARY KEY (
		MAIL_THREAD_SID
		)
;

ALTER TABLE MEMBER_ROLE
	ADD CONSTRAINT MEMBER_ROLE_PK PRIMARY KEY (
		MEMBER_ROLE_SID
		)
;

ALTER TABLE THREAD_TYPE
	ADD CONSTRAINT THREAD_TYPE_PK PRIMARY KEY (
		THREAD_TYPE_SID
		)
;

ALTER TABLE LOCATION_ACCURACY
	ADD CONSTRAINT LOCATION_ACCURACY_PK PRIMARY KEY (
		LOCATION_ACCURACY_SID
		)
;

ALTER TABLE MEMBER_ASSOCIATION_TYPE
	ADD CONSTRAINT MEMBER_ASSOCIATION_TYPE_PK PRIMARY KEY (
		MEMBER_ASSOCIATION_TYPE_SID
		)
;

ALTER TABLE ITEM_BUNDLE_I18N
	ADD CONSTRAINT ITEM_BUNDLE_I18N_PK PRIMARY KEY (
		ITEM_BUNDLE_I18N_SID
		)
;

ALTER TABLE ITEM_TYPE
	ADD CONSTRAINT ITEM_TYPE_PK PRIMARY KEY (
		ITEM_TYPE_SID
		)
;

ALTER TABLE EVENT_VALUE
	ADD CONSTRAINT EVENT_VALUE_PK PRIMARY KEY (
		EVENT_VALUE_SID
		)
;

ALTER TABLE DIFFUSED_ITEM_TYPE
	ADD CONSTRAINT DIFFUSED_ITEM_TYPE_PK PRIMARY KEY (
		DIFFUSED_ITEM_TYPE_SID
		)
;

ALTER TABLE JOB_HISTORY
	ADD CONSTRAINT JOB_HISTORY_PK PRIMARY KEY (
		JOB_HISTORY_SID
		)
;

ALTER TABLE GROUP_MEMBER
	ADD CONSTRAINT GROUP_MEMBER_PK PRIMARY KEY (
		GROUP_MEMBER_SID
		)
;

ALTER TABLE TAG
	ADD CONSTRAINT TAG_PK PRIMARY KEY (
		TAG_SID
		)
;

ALTER TABLE PERMISSION
	ADD CONSTRAINT PERMISSION_PK PRIMARY KEY (
		PERMISSION_SID
		)
;

ALTER TABLE SCHEDULE_INFO
	ADD CONSTRAINT SCHEDULE_INFO_PK PRIMARY KEY (
		SCHEDULE_INFO_SID
		)
;

ALTER TABLE DIALOG
	ADD CONSTRAINT DIALOG_PK PRIMARY KEY (
		DIALOG_SID
		)
;

ALTER TABLE IDENTITY_EVENT
	ADD CONSTRAINT IDENTITY_EVENT_PK PRIMARY KEY (
		IDENTITY_EVENT_SID
		)
;

ALTER TABLE PROJECT_ACCESS_TYPE
	ADD CONSTRAINT PROJECT_ACCESS_TYPE_PK PRIMARY KEY (
		PROJECT_ACCESS_TYPE_SID
		)
;

ALTER TABLE INVOICE_ASSET
	ADD CONSTRAINT INVOICE_ASSET_PK PRIMARY KEY (
		INVOICE_ARTICLE_ASS_SID
		)
;

ALTER TABLE SCHEDULE
	ADD CONSTRAINT SCHEDULE_PK PRIMARY KEY (
		SCHEDULE_SID
		)
;

ALTER TABLE MEMBER_ASSOCIATION
	ADD CONSTRAINT MEMBER_ASSOCIATION_PK PRIMARY KEY (
		MEMBER_ASSOCIATION_SID
		)
;

ALTER TABLE RESOURCE
	ADD CONSTRAINT RESOURCE_PK PRIMARY KEY (
		RESOURCE_SID
		)
;

ALTER TABLE INVOICE_ACCOUNTING
	ADD CONSTRAINT INVOICE_ACCOUNTING_FK PRIMARY KEY (
		INVOICE_ACCOUNTING_SID
		)
;

ALTER TABLE DIALOG_COMMENT
	ADD CONSTRAINT DIALOG_DIALOG_COMMENT_PK PRIMARY KEY (
		DIALOG_COMMENT_SID
		)
;

ALTER TABLE DIFFUSION
	ADD CONSTRAINT DIFFUSION_PK PRIMARY KEY (
		DIFFUSION_SID
		)
;

ALTER TABLE MEMBER_EVENT
	ADD CONSTRAINT MEMBER_EVENT_PK PRIMARY KEY (
		MEMBER_EVENT_SID
		)
;

ALTER TABLE COMMUNITY_TYPE
	ADD CONSTRAINT COMMUNITY_TYPE_PK PRIMARY KEY (
		COMMUNITY_TYPE_SID
		)
;

ALTER TABLE INVOICE
	ADD CONSTRAINT INVOICE_PK PRIMARY KEY (
		INVOICE_SID
		)
;

ALTER TABLE MEMBER_ACCESS_TYPE
	ADD CONSTRAINT MEMBER_ACCESS_TYPE_PK PRIMARY KEY (
		MEMBER_ACCESS_TYPE_SID
		)
;

ALTER TABLE SCHEDULE_PARTICIPANT
	ADD CONSTRAINT SCHEDULE_PARTICIPANT_PK PRIMARY KEY (
		SCHEDULE_PARTICIPANT_SID
		)
;

ALTER TABLE SUBSCRIPTION
	ADD CONSTRAINT SUBSCRIPTION_PK PRIMARY KEY (
		SUBSCRIPTION_SID
		)
;

ALTER TABLE SCHEMA_INFO
	ADD CONSTRAINT SCHEMA_INFO_PK PRIMARY KEY (
		SCHEMA_INFO_SID
		)
;

ALTER TABLE SUBSCRIPTION_FILTER
	ADD CONSTRAINT SUBSCRIPTION_FILTER_PK PRIMARY KEY (
		SUBSCRIPTION_FILTER_SID
		)
;

ALTER TABLE EVENT
	ADD CONSTRAINT EVENT_PK PRIMARY KEY (
		EVENT_SID
		)
;

ALTER TABLE ITEM_BUNDLE_TYPE
	ADD CONSTRAINT ITEM_BUNDLE_TYPE_PK PRIMARY KEY (
		ITEM_BUNDLE_TYPE_SID
		)
;

ALTER TABLE IDENTITY_VALUE
	ADD CONSTRAINT IDENTITY_VALUE_PK PRIMARY KEY (
		IDENTITY_VALUE_SID
		)
;

ALTER TABLE ITEM_TAG
	ADD CONSTRAINT ITEM_TAG_PK PRIMARY KEY (
		ITEM_TAG_SID
		)
;

ALTER TABLE DIFFUSED_ITEM
	ADD CONSTRAINT DIFFUSED_ITEM_PK PRIMARY KEY (
		DIFFUSED_ITEM_SID
		)
;

ALTER TABLE MEMBER_FOLLOW
	ADD CONSTRAINT MEMBER_FOLLOW_PK PRIMARY KEY (
		MEMBER_FOLLOW_SID
		)
;

ALTER TABLE IDENTITY_ACCESS_TYPE
	ADD CONSTRAINT IDENTITY_ACCESS_TYPE_PK PRIMARY KEY (
		IDENTITY_ACCESS_TYPE_SID
		)
;

ALTER TABLE TELEPHONE
	ADD CONSTRAINT TELEPHONE_PK PRIMARY KEY (
		TELEPHONE_SID
		)
;

ALTER TABLE MEMBER
	ADD CONSTRAINT MEMBER_PK PRIMARY KEY (
		MEMBER_SID
		)
;

ALTER TABLE IDENTITY_INFO
	ADD CONSTRAINT IDENTITY_INFO_PK PRIMARY KEY (
		IDENTITY_INFO_SID
		)
;

ALTER TABLE ACTION
	ADD CONSTRAINT ACTION_PK PRIMARY KEY (
		ACTION_SID
		)
;

ALTER TABLE JOB_ASSIGNMENT
	ADD CONSTRAINT JOB_ASSIGNMENT_PK PRIMARY KEY (
		JOB_ASSIGNMENT_SID
		)
;

ALTER TABLE COMMUNITY_EVENT
	ADD CONSTRAINT COMMUNITY_EVENT_PK PRIMARY KEY (
		COMMUNITY_EVENT_SID
		)
;

ALTER TABLE INVOICE_ACTION
	ADD CONSTRAINT INVOICE_ACTION_PK PRIMARY KEY (
		INVOICE_ACTION_SID
		)
;

ALTER TABLE IDENTITY
	ADD CONSTRAINT IDENTITY_PK PRIMARY KEY (
		IDENTITY_SID
		)
;

ALTER TABLE IDENTITY
	ADD CONSTRAINT IDENTITY_IDENTITY_LOGIN_SYSTEM_UN UNIQUE (
		IDENTITY_LOGIN_SYSTEM
		)
;

ALTER TABLE PROJECT
	ADD CONSTRAINT PROJECT_COMMUNTIY_SID_PROJECT_CODE_UN UNIQUE (
		COMMUNITY_SID,
		PROJECT_CODE
		)
;

ALTER TABLE PROJECT
	ADD CONSTRAINT PROJECT_PK PRIMARY KEY (
		PROJECT_SID
		)
;

ALTER TABLE EVENT_TYPE
	ADD CONSTRAINT EVENT_TYPE_FK PRIMARY KEY (
		EVENT_TYPE_SID
		)
;

ALTER TABLE GROUP
	ADD CONSTRAINT GROUPE_GROUP_CODE_UN UNIQUE (
		GROUP_CODE
		)
;

ALTER TABLE GROUP
	ADD CONSTRAINT GROUP_PK PRIMARY KEY (
		GROUP_SID
		)
;

ALTER TABLE DIALOG_STATUS
	ADD CONSTRAINT DIALOG_STATUS_PK PRIMARY KEY (
		DIALOG_STATUS_SID
		)
;

ALTER TABLE ROLE
	ADD CONSTRAINT ROLE_PK PRIMARY KEY (
		ROLE_SID
		)
;

ALTER TABLE COMMUNITY_ACCESS_TYPE
	ADD CONSTRAINT COMMUNITY_ACCESS_TYPE_PK PRIMARY KEY (
		COMMUNITY_ACCESS_TYPE_SID
		)
;

ALTER TABLE URL_TYPE
	ADD CONSTRAINT URL_TYPE_PK PRIMARY KEY (
		URL_TYPE_SID
		)
;

ALTER TABLE MEMBER_STATUS
	ADD CONSTRAINT MEMBER_STATUS_PK PRIMARY KEY (
		MEMBER_STATUS_SID
		)
;

ALTER TABLE RELATION
	ADD CONSTRAINT RELATION_PK PRIMARY KEY (
		RELATION_SID
		)
;

ALTER TABLE INVOICE_ACCOUNT
	ADD CONSTRAINT INVOICE_ACCOUNT_PK PRIMARY KEY (
		INVOICE_ACCOUNT_SID
		)
;

ALTER TABLE JOB
	ADD CONSTRAINT JOB_PK PRIMARY KEY (
		JOB_SID
		)
;

ALTER TABLE DRIVER
	ADD CONSTRAINT DRIVER_PK PRIMARY KEY (
		DRIVER_SID
		)
;

ALTER TABLE COMMUNITY
	ADD CONSTRAINT COMMUNITY_COMMUNITY_CODE_UN UNIQUE (
		COMMUNITY_CODE
		)
;

ALTER TABLE COMMUNITY
	ADD CONSTRAINT COMMUNITY_PK PRIMARY KEY (
		COMMUNITY_SID
		)
;

ALTER TABLE PROJECT_INFO
	ADD CONSTRAINT PROJECT_INFO_PK PRIMARY KEY (
		PROJECT_INFO_SID
		)
;

ALTER TABLE ADDRESS
	ADD CONSTRAINT ADDRESS_PK PRIMARY KEY (
		ADDRESS_SID
		)
;

ALTER TABLE DRIVER_TYPE
	ADD CONSTRAINT DRIVER_TYPE_PK PRIMARY KEY (
		DRIVER_TYPE_SID
		)
;

ALTER TABLE GROUP_ACCESS_TYPE
	ADD CONSTRAINT GROUP_ACCESS_TYPE_PK PRIMARY KEY (
		GROUP_ACCESS_TYPE_SID
		)
;

ALTER TABLE COMMUNITY_API
	ADD CONSTRAINT COMMUNITY_API_PK PRIMARY KEY (
		COMMUNITY_API_SID
		)
;

ALTER TABLE DIALOG_TYPE
	ADD CONSTRAINT DIALOG_TYPE_PK PRIMARY KEY (
		DIALOG_TYPE_SID
		)
;

ALTER TABLE STAT
	ADD CONSTRAINT STAT_PK PRIMARY KEY (
		STAT_SID
		)
;

ALTER TABLE JOB_RESOURCE_ASSIG
	ADD CONSTRAINT JOB_RESOURCE_ASSIG_PK PRIMARY KEY (
		JOB_RESOURCE_ASSIG_SID
		)
;
