ALTER TABLE EVENT
	ADD CONSTRAINT EVE_Constraint2 FOREIGN KEY (
		DIFFUSION_ID
		)
	REFERENCES DIFFUSION (
		ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE EVENT
	ADD CONSTRAINT EVE_Constraint1 FOREIGN KEY (
		ITEM_DIFFUSED_SID
		)
	REFERENCES ITEM_DIFFUSED (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE JOB_HISTORY_INFO
	ADD CONSTRAINT JOB_Constraint9 FOREIGN KEY (
		JOB_HISTORY_ID
		)
	REFERENCES JOB_HISTORY (
		JOB_HISTORY_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE TELEPHONE
	ADD CONSTRAINT TEL_Constraint1 FOREIGN KEY (
		COMPANY_ID
		)
	REFERENCES COMPANY (
		COMPANY_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE DOCUMENT_VERSION
	ADD CONSTRAINT FK_DOC_VERSION_2 FOREIGN KEY (
		DOCUMENT_ID
		)
	REFERENCES DOCUMENT (
		DOCUMENT_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE MEMBER
	ADD CONSTRAINT MEMB_B FOREIGN KEY (
		COMMUNITY_ID
		)
	REFERENCES COMMUNITY (
		COMMUNITY_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE MEMBER
	ADD CONSTRAINT MEM_Constraint1 FOREIGN KEY (
		COMPANY_ID
		)
	REFERENCES COMPANY (
		COMPANY_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE JOB_ASSIGNMENT
	ADD CONSTRAINT JOB_Constraint10 FOREIGN KEY (
		JOB_ID
		)
	REFERENCES JOB (
		JOB_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE JOB_ASSIGNMENT
	ADD CONSTRAINT JOB_Constraint2 FOREIGN KEY (
		JOB_JOB_ID
		)
	REFERENCES JOB (
		JOB_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE JOB
	ADD CONSTRAINT JOB_Constraint3 FOREIGN KEY (
		EXECUTANT_ID
		)
	REFERENCES MEMBER (
		MEMBER_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE JOB
	ADD CONSTRAINT JOB_Constraint12 FOREIGN KEY (
		CREATOR_ID
		)
	REFERENCES MEMBER (
		MEMBER_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE JOB
	ADD CONSTRAINT JOB_Constraint11 FOREIGN KEY (
		PARENT_JOB_ID
		)
	REFERENCES JOB (
		JOB_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE JOB
	ADD CONSTRAINT FK_JOB_4 FOREIGN KEY (
		PROJECT_ID
		)
	REFERENCES PROJECT (
		PROJECT_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE COMMUNITY
	ADD CONSTRAINT COMUNI_A1 FOREIGN KEY (
		COMMUNITY_TYPE_ID
		)
	REFERENCES COMMUNITY_TYPE (
		ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE DATE_COMPANY_ASSIG
	ADD CONSTRAINT FK_DATE_COMP_1 FOREIGN KEY (
		DATE_ID
		)
	REFERENCES DATE_X (
		DATE_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE PROJECT_INFO
	ADD CONSTRAINT FK_PROJECT_INFO_1 FOREIGN KEY (
		PROJECT_ID
		)
	REFERENCES PROJECT (
		PROJECT_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ADDRESS
	ADD CONSTRAINT ADD_Constraint1 FOREIGN KEY (
		COMPANY_ID
		)
	REFERENCES COMPANY (
		COMPANY_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE DOCUMENT
	ADD CONSTRAINT FK_DOCUMENT_5 FOREIGN KEY (
		PARENT_DOCUMENT_ID
		)
	REFERENCES DOCUMENT (
		DOCUMENT_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE DOCUMENT
	ADD CONSTRAINT FK_DOCUMENT_3 FOREIGN KEY (
		PROJECT_ID
		)
	REFERENCES PROJECT (
		PROJECT_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE DOCUMENT
	ADD CONSTRAINT FK_DOCUMENT_2 FOREIGN KEY (
		DATE_ID
		)
	REFERENCES DATE_X (
		DATE_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE JOB_RESOURCE_ASSIG
	ADD CONSTRAINT FK_JOB_RES_ASS_2 FOREIGN KEY (
		RESOURCE_ID
		)
	REFERENCES RESOURCE (
		RESOURCE_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE JOB_RESOURCE_ASSIG
	ADD CONSTRAINT JOB_Constraint13 FOREIGN KEY (
		JOB_ID
		)
	REFERENCES JOB (
		JOB_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE PROJECT_MEMBER_ASS
	ADD CONSTRAINT PRO_Constraint2 FOREIGN KEY (
		PROJECT_ID
		)
	REFERENCES PROJECT (
		PROJECT_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE PROJECT_MEMBER_ASS
	ADD CONSTRAINT PRO_Constraint1 FOREIGN KEY (
		MEMBER_ID
		)
	REFERENCES MEMBER (
		MEMBER_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ASSET_VALUE
	ADD CONSTRAINT ASS_Constraint2 FOREIGN KEY (
		ASSET_SID
		)
	REFERENCES ASSET (
		ASSET_SID
		)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM_TYPE
	ADD CONSTRAINT ITE_D_Cons FOREIGN KEY (
		ITEM_DIFF_TYPE_SID
		)
	REFERENCES ITEM_DIFFUSED_TYPE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE COMPANY_LG_ASS
	ADD CONSTRAINT COM_Constraint14 FOREIGN KEY (
		COMPANY_ID
		)
	REFERENCES COMPANY (
		COMPANY_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE COMPANY_LG_ASS
	ADD CONSTRAINT COM_Constraint3 FOREIGN KEY (
		LANGUAGE_SID
		)
	REFERENCES LANGUAGE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ASSET_PHOTO
	ADD CONSTRAINT ASS_Constraint15 FOREIGN KEY (
		ASSET_SID
		)
	REFERENCES ASSET (
		ASSET_SID
		)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM_BUNDLE_I18N
	ADD CONSTRAINT ITE_Constraint16 FOREIGN KEY (
		ITEM_BUNDLE_SID
		)
	REFERENCES ITEM_BUNDLE (
		SID
		)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM_BUNDLE_I18N
	ADD CONSTRAINT ITE_B_L_Con3 FOREIGN KEY (
		LANGUAGE_SID
		)
	REFERENCES LANGUAGE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE SKIN_ASS
	ADD CONSTRAINT SKI_Constraint2 FOREIGN KEY (
		COMMUNITY_ID
		)
	REFERENCES COMMUNITY (
		COMMUNITY_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE SKIN_ASS
	ADD CONSTRAINT SKI_Constraint1 FOREIGN KEY (
		SKIN_SID
		)
	REFERENCES SKIN (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM_BUNDLE
	ADD CONSTRAINT ITE_Constraint19 FOREIGN KEY (
		SKIN_SID
		)
	REFERENCES SKIN (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM_BUNDLE
	ADD CONSTRAINT ITE_Constraint18 FOREIGN KEY (
		MEMBER_ID
		)
	REFERENCES MEMBER (
		MEMBER_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM_BUNDLE
	ADD CONSTRAINT ITE_Constraint17 FOREIGN KEY (
		ITEM_BUNDLE_TY_SID
		)
	REFERENCES ITEM_BUNDLE_TYPE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM_I18N
	ADD CONSTRAINT ITE_Constraint21 FOREIGN KEY (
		LANGUAGE_SID
		)
	REFERENCES LANGUAGE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM_I18N
	ADD CONSTRAINT ITE_Constraint20 FOREIGN KEY (
		ITEM_SID
		)
	REFERENCES ITEM (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE SKIN
	ADD CONSTRAINT SKIN_1 FOREIGN KEY (
		SKIN_TYPE_SID
		)
	REFERENCES SKIN_TYPE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE MEMBER_ROLE_ASS
	ADD CONSTRAINT MEM_Constraint3 FOREIGN KEY (
		MEMBER_ID
		)
	REFERENCES MEMBER (
		MEMBER_ID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE MEMBER_ROLE_ASS
	ADD CONSTRAINT MEM_Constraint2 FOREIGN KEY (
		ROLE_SID
		)
	REFERENCES ROLE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM
	ADD CONSTRAINT IT_Constr3 FOREIGN KEY (
		ITEM_TYPE_SID
		)
	REFERENCES ITEM_TYPE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM
	ADD CONSTRAINT ITE_Constraint23 FOREIGN KEY (
		ASSET_SID
		)
	REFERENCES ASSET (
		ASSET_SID
		)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM
	ADD CONSTRAINT ITE_Constraint22 FOREIGN KEY (
		ITEM_SID
		)
	REFERENCES ITEM (
		SID
		)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM
	ADD CONSTRAINT IT_Constr2 FOREIGN KEY (
		STATUS_TYPE_SID
		)
	REFERENCES STATUS_TYPE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ASSET
	ADD CONSTRAINT ASS_Constraint3 FOREIGN KEY (
		ASSET_LANG_SID
		)
	REFERENCES LANGUAGE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ASSET
	ADD CONSTRAINT ASS_Constraint24 FOREIGN KEY (
		ASSET_TYPE_SID
		)
	REFERENCES ASSET_TYPE (
		SID
		)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
;

ALTER TABLE ASSET
	ADD CONSTRAINT ASS_Constraint4 FOREIGN KEY (
		ASSET_ADDRESS_ID
		)
	REFERENCES ADDRESS (
		ADDRESS_ID
		)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM_BUNDLE_ASS
	ADD CONSTRAINT ITE_Constraint26 FOREIGN KEY (
		ITEM_SID
		)
	REFERENCES ITEM (
		SID
		)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
;

ALTER TABLE ITEM_BUNDLE_ASS
	ADD CONSTRAINT ITE_Constraint25 FOREIGN KEY (
		ITEM_BUNDLE_SID
		)
	REFERENCES ITEM_BUNDLE (
		SID
		)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
;


