INSERT INTO SCHEDULE (MEMBER_ID,SCHECULE_TYPE_SID ,START_DATE,END_DATE,TITLE) VALUES (1, 1, CURRENT TIMESTAMP, CURRENT TIMESTAMP, 'SAMPLE TITLE');

INSERT INTO SCHEDULE_INFO (SCHEDULE_ID,COMMENT) VALUES (1, 'SAMPLE COMMENT'); 
