INSERT INTO ITEM_BUNDLE_TYPE ( SID, NAME , DESCRIPTION) VALUES (6,'ITEM_BUNDLE_MESSAGES','messages des mails eCards en tetes subject');
INSERT INTO ITEM_BUNDLE (SID, NAME, DESCRIPTION, URL, SKIN_ID, MEMBER_ID, ITEM_BUNDLE_TY_SID) VALUES (2,'umg_voeux_2006','U-MANGATE VOEUX 2006','http://ecards.umg.be',5,, 4);
