INSERT INTO DELIVERABLE (DELIVR_NAME, DELIVR_COMMENT, DELIVR_DATE, DELIVR_DATE_RULE) VALUES ('Name', 'Comment', '2006-03-29', 'Rule');
INSERT INTO DELIVERABLE (DELIVR_NAME, DELIVR_COMMENT, DELIVR_DATE, DELIVR_DATE_RULE) VALUES ('Name', 'Comment', '2006-03-29 13:01:23.123456', 'Rule');
