-- Derby doesn't support IF EXISTS condition on DROP TABLE...

-- DROP TABLE CUSTOMER;
DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
  FIRST_NAME CHAR(50),
  LAST_NAME CHAR(50),
  ADDRESS CHAR(50),
  CITY CHAR(50),
  COUNTRY CHAR(25),
  START_DATE DATE,
  BIRTH_DATE TIMESTAMP
);

-- DROP TABLE CITY_ALIAS;
DROP TABLE IF EXISTS CITY_ALIAS;
CREATE TABLE CITY_ALIAS (
  CITY_ALIAS CHAR(50),
  REAL_CITY CHAR(50)
);

-- DROP TABLE REAL_CITY;
DROP TABLE IF EXISTS REAL_CITY;
CREATE TABLE REAL_CITY (
  REAL_CITY CHAR(50),
  ZIP INTEGER
);

-- INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, ADDRESS, CITY, COUNTRY, START_DATE, BIRTH_DATE)
--   VALUES ('fn1', 'ln1', 'add1', 'cit1', 'co1', DATE(2001-01-01), TIMESTAMP('1962-09-23 03:23:34.234'));
-- INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, ADDRESS, CITY, COUNTRY, START_DATE, BIRTH_DATE)
--   VALUES ('fn1', 'ln1', 'add1', 'cit2', 'co2', DATE(2001-01-01), TIMESTAMP('1962-09-23 03:23:34.234'));
-- INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, ADDRESS, CITY, COUNTRY, START_DATE, BIRTH_DATE)
--   VALUES ('fn3', 'ln3', 'add3', 'cit3', 'co3', DATE(2001-01-01), TIMESTAMP('1962-09-23 03:23:34.234'));
-- INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, ADDRESS, CITY, COUNTRY, START_DATE, BIRTH_DATE)
--   VALUES ('fn4', 'ln4', 'add4', 'real_cit4', 'co4', DATE(2001-01-01), TIMESTAMP('1962-09-23 03:23:34.234'));
-- INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, ADDRESS, CITY, COUNTRY, START_DATE, BIRTH_DATE)
--   VALUES ('fn5', 'ln5', 'add5', 'cit5', 'co5', DATE(2001-01-01), TIMESTAMP('1962-09-23 03:23:34.234'));
-- INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, ADDRESS, CITY, COUNTRY, START_DATE, BIRTH_DATE)
--   VALUES ('fn6', 'ln6', 'add6', 'real_cit6', 'co6', DATE(2001-01-01), TIMESTAMP('1962-09-23 03:23:34.234'));

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, ADDRESS, CITY, COUNTRY, START_DATE, BIRTH_DATE)
  VALUES ('fn1', 'ln1', 'add1', 'cit1', 'co1', NULL, NULL);
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, ADDRESS, CITY, COUNTRY, START_DATE, BIRTH_DATE)
  VALUES ('fn1', 'ln1', 'add1', 'cit2', 'co2', NULL, NULL);
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, ADDRESS, CITY, COUNTRY, START_DATE, BIRTH_DATE)
  VALUES ('fn3', 'ln3', 'add3', 'cit3', 'co3', NULL, NULL);
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, ADDRESS, CITY, COUNTRY, START_DATE, BIRTH_DATE)
  VALUES ('fn4', 'ln4', 'add4', 'real_cit4', 'co4', NULL, NULL);
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, ADDRESS, CITY, COUNTRY, START_DATE, BIRTH_DATE)
  VALUES ('fn5', 'ln5', 'add5', 'cit5', 'co5', NULL, NULL);
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, ADDRESS, CITY, COUNTRY, START_DATE, BIRTH_DATE)
  VALUES ('fn6', 'ln6', 'add6', 'real_cit6', 'co6', NULL, NULL);

-- We want a positive join on cit1/real_cit1, cit1/real_cit1bis, cit2/real_cit2, real_cit4

INSERT INTO CITY_ALIAS (CITY_ALIAS, REAL_CITY)
  VALUES ('cit1','real_cit1');
INSERT INTO CITY_ALIAS (CITY_ALIAS, REAL_CITY)
  VALUES ('cit1','real_cit1bis');
INSERT INTO CITY_ALIAS (CITY_ALIAS, REAL_CITY)
  VALUES ('cit2','real_cit2');

INSERT INTO REAL_CITY (REAL_CITY, ZIP)
  VALUES ('real_cit1', 10);
INSERT INTO REAL_CITY (REAL_CITY, ZIP)
  VALUES ('real_cit1bis', 11);
INSERT INTO REAL_CITY (REAL_CITY, ZIP)
  VALUES ('real_cit2', 20);
INSERT INTO REAL_CITY (REAL_CITY, ZIP)
  VALUES ('real_cit3', 30);
INSERT INTO REAL_CITY (REAL_CITY, ZIP)
  VALUES ('real_cit4', 40);

SELECT cst.FIRST_NAME, cst.CITY, ca.CITY_ALIAS 
 FROM CUSTOMER cst 
 JOIN CITY_ALIAS ca ON cst.CITY = ca.CITY_ALIAS;

SELECT cst.FIRST_NAME, ca.CITY_ALIAS, ci.REAL_CITY, ci.ZIP 
 FROM CUSTOMER cst 
 JOIN CITY_ALIAS ca ON cst.CITY = ca.CITY_ALIAS
 JOIN REAL_CITY ci ON ca.REAL_CITY = ci.REAL_CITY;

SELECT ca.CITY_ALIAS, ci.REAL_CITY, ci.ZIP 
  FROM CITY_ALIAS ca
  LEFT OUTER JOIN REAL_CITY ci
  ON ca.REAL_CITY = ci.REAL_CITY;

SELECT COALESCE(ca.CITY_ALIAS, ca.REAL_CITY) FROM CITY_ALIAS ca;

SELECT *
  FROM REAL_CITY ci
  FULL OUTER JOIN CITY_ALIAS ca
  ON ci.REAL_CITY = ca.REAL_CITY;

SELECT *
  FROM REAL_CITY ci
  FULL OUTER JOIN CITY_ALIAS ca
  ON ci.REAL_CITY = ca.REAL_CITY
  WHERE ca.CITY_ALIAS IS NULL 
    OR ci.ZIP IS NULL;

SELECT *
  FROM CITY_ALIAS ca
  FULL OUTER JOIN REAL_CITY ci
  ON ci.REAL_CITY = ca.REAL_CITY
  WHERE ca.CITY_ALIAS IS NULL 
    OR ci.ZIP IS NULL;

SELECT * FROM (
  SELECT CITY_ALIAS.CITY_ALIAS, CITY_ALIAS.REAL_CITY AS rc1, REAL_CITY.REAL_CITY AS rc2, REAL_CITY.ZIP FROM CITY_ALIAS LEFT OUTER JOIN REAL_CITY ON CITY_ALIAS.REAL_CITY = REAL_CITY.REAL_CITY
    UNION 
  SELECT CITY_ALIAS.CITY_ALIAS, CITY_ALIAS.REAL_CITY AS rc1, REAL_CITY.REAL_CITY AS rc2, REAL_CITY.ZIP FROM REAL_CITY LEFT OUTER JOIN CITY_ALIAS ON CITY_ALIAS.REAL_CITY = REAL_CITY.REAL_CITY
) a;

SELECT cst.FIRST_NAME, ca.CITY_ALIAS, ca.REAL_CITY, ca.ZIP 
 FROM CUSTOMER cst 
 JOIN (
    SELECT ci.REAL_CITY, ci.ZIP, ca.CITY_ALIAS FROM REAL_CITY ci
      LEFT OUTER JOIN CITY_ALIAS ca
      ON ca.REAL_CITY = ci.REAL_CITY
 ) ca 
 ON cst.CITY = COALESCE(ca.REAL_CITY, ca.CITY_ALIAS);
