ALTER TABLE PERSON DROP CONSTRAINT PERSON_FAMILY_ID
ALTER TABLE PERSON_JOB DROP CONSTRAINT PERSONJOBjobListID
ALTER TABLE PERSON_JOB DROP CONSTRAINT PERSONJOBPerson_ID
DROP TABLE FAMILY
DROP TABLE PERSON
DROP TABLE PERSON_JOB
DROP TABLE JOB
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN_TABLE'
