CALL SYSCS_UTIL.SYSCS_INPLACE_COMPRESS_TABLE('AOS', 'MEMBER_EVENT', 1, 1, 1);
CALL SYSCS_UTIL.SYSCS_INPLACE_COMPRESS_TABLE('AOS', 'MEMBER', 1, 1, 1);
CALL SYSCS_UTIL.SYSCS_INPLACE_COMPRESS_TABLE('AOS', 'IDENTITY', 1, 1, 1);
CALL SYSCS_UTIL.SYSCS_INPLACE_COMPRESS_TABLE('AOS', 'SUBSCRIPTION', 1, 1, 1);
