/****************************************************************
 * Licensed to the AOS Community (AOS) under one or more        *
 * contributor license agreements.  See the NOTICE file         *
 * distributed with this work for additional information        *
 * regarding copyright ownership.  The AOS licenses this file   *
 * to you under the Apache License, Version 2.0 (the            *
 * "License"); you may not use this file except in compliance   *
 * with the License.  You may obtain a copy of the License at   *
 *                                                              *
 *   http://www.apache.org/licenses/LICENSE-2.0                 *
 *                                                              *
 * Unless required by applicable law or agreed to in writing,   *
 * software distributed under the License is distributed on an  *
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY       *
 * KIND, either express or implied.  See the License for the    *
 * specific language governing permissions and limitations      *
 * under the License.                                           *
 ****************************************************************/
package io.datalayer.sql.jdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.util.Date;

import org.junit.Test;

public class JdbcSimpleTest {
    private static final String JDBC_URL = "jdbc:derby:memory:TestDatabase;create=true";

    private static final String CREATE_SQL = "CREATE TABLE MAPS ( " //
            + " MAP_ID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), " //
            + " MAP_NAME VARCHAR(24) NOT NULL, " //
            + " REGION VARCHAR(26), " //
            + " AREA DECIMAL(8,4) NOT NULL, " //
            + " PHOTO_FORMAT VARCHAR(26) NOT NULL, " //
            + " UNIQUE (MAP_ID, MAP_NAME) " //
            + " )";

    private static final String INSERT_SQL = "INSERT INTO MAPS " //
            + " (MAP_NAME, REGION, AREA, PHOTO_FORMAT) " //
            + " VALUES " //
            + " ('MAP1', 'REGION1', 3, 'FORMAT1')";

    private static final String SELECT_SQL = "SELECT * FROM MAPS";

    @Test
    public void test() throws SQLException {

        Connection connection = DriverManager.getConnection(JDBC_URL);
        System.out.println("autocommit=" + connection.getAutoCommit());

        Statement stmt = connection.createStatement();
        System.out.println(stmt.execute(CREATE_SQL) + ": " + CREATE_SQL);
        System.out.println(stmt.execute(INSERT_SQL) + ": " + INSERT_SQL);

        stmt = connection.createStatement();
        ResultSet rs = stmt.executeQuery(SELECT_SQL);
        System.out.println(SELECT_SQL);
        while (rs.next()) {
            System.out.printf("map_id:%s | map_name:%s | area:%d | region:%s\n", //
                    rs.getInt("MAP_ID"), rs.getString("MAP_NAME"), rs.getLong("AREA"), rs.getString("REGION"));
        }

        rs.close();
        connection.close();

    }
    
    public static Date toDate(java.sql.Date date, Time time) {
        return new Date(date.getTime() + time.getTime());
    }

}
