UPDATE ITEM_BUNDLE_ASS SET ITEM_BUNDLE_SID = 22 WHERE SID = 3;
UPDATE ITEM_BUNDLE_ASS SET ITEM_BUNDLE_SID = 22 WHERE SID = 4;
UPDATE ITEM_BUNDLE_ASS SET ITEM_BUNDLE_SID = 22 WHERE SID = 5;
UPDATE ITEM_BUNDLE_ASS SET ITEM_BUNDLE_SID = 22 WHERE SID = 6;
UPDATE ITEM_BUNDLE_ASS SET ITEM_BUNDLE_SID = 22 WHERE SID = 7;
UPDATE ITEM_BUNDLE_ASS SET ITEM_BUNDLE_SID = 22 WHERE SID = 8;
