Received: by 10.229.98.142 with SMTP id q14cs612284qcn;
        Tue, 22 Dec 2009 10:13:30 -0800 (PST)
Return-Path: <g.giridharkannan@gmail.com>
Received-SPF: pass (google.com: domain of g.giridharkannan@gmail.com designates 10.150.248.42 as permitted sender) client-ip=10.150.248.42;
Authentication-Results: mr.google.com; spf=pass (google.com: domain of g.giridharkannan@gmail.com designates 10.150.248.42 as permitted sender) smtp.mail=g.giridharkannan@gmail.com
Received: from mr.google.com ([10.150.248.42])
        by 10.150.248.42 with SMTP id v42mr654705ybh.4.1261505609988 (num_hops = 1);
        Tue, 22 Dec 2009 10:13:29 -0800 (PST)
MIME-Version: 1.0
Received: by 10.150.248.42 with SMTP id v42mr654705ybh.4.1261505609985; Tue, 
	22 Dec 2009 10:13:29 -0800 (PST)
Date: Tue, 22 Dec 2009 10:13:29 -0800 (PST)
In-Reply-To: <7b3b2550-0288-4303-8081-871ca0e5f66d@u25g2000prh.googlegroups.com>
X-IP: 115.184.110.220
References: <7b3b2550-0288-4303-8081-871ca0e5f66d@u25g2000prh.googlegroups.com>
User-Agent: G2/1.0
X-HTTP-UserAgent: Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.1.3) 
	Gecko/20091020 Ubuntu/9.10 (karmic) Firefox/3.5.3,gzip(gfe),gzip(gfe)
Message-ID: <15d8f1a8-5ed8-4feb-a44d-e538910e2f6d@u25g2000prh.googlegroups.com>
Subject: Fwd: integrating openid in website using java
From: giridhar kannan <g.giridharkannan@gmail.com>
To: "g.giridharkannan" <g.giridharkannan@gmail.com>
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable




---------- Forwarded message ----------
From: giridhar kannan <g.giridharkan...@gmail.com>
Date: Dec 22, 7:55=A0pm
Subject: integrating openid in website using java
To: Google App Engine


hello,
=A0 =A0 =A0 =A0I am giridhar kannan working on app engine. I would like to
know how to integrate a website with openid authentication using java.
Please do help me in this regard.
Thank you.