SELECT SYS.SYSTABLES.TABLENAME, SYS.SYSCONGLOMERATES.CONGLOMERATENAME, SYS.SYSCONGLOMERATES.ISCONSTRAINT FROM SYS.SYSTABLES, SYS.SYSCONGLOMERATES WHERE SYS.SYSTABLES.TABLEID = SYS.SYSCONGLOMERATES.TABLEID AND SYS.SYSTABLES.TABLENAME = 'MEMBER_EVENT';

SELECT SYS.SYSTABLES.TABLENAME FROM SYS.SYSTABLES;

SELECT SYS.SYSCONSTRAINTS.CONSTRAINTNAME, SYS.SYSCONSTRAINTS.TYPE FROM SYS.SYSTABLES, SYS.SYSCONSTRAINTS WHERE SYS.SYSTABLES.TABLEID = SYS.SYSCONSTRAINTS.TABLEID AND SYS.SYSTABLES.TABLENAME = 'IDENTITY';
