CREATE TABLE JOB_HISTORY (
	JOB_HISTORY_SID INTEGER NOT NULL,
	OBJECT_VERSION INTEGER,
	ACTOR_ID INTEGER,
	ACTION VARCHAR ( 50 ),
	ACTION_DATE TIMESTAMP,
	JOB_STATUS VARCHAR ( 50 ),
	DB_STATUS VARCHAR ( 50 ),
	JOB_SID_HISTORY INTEGER NOT NULL
	)
;
